### ISSUE TITLE
inner favorite

### ISSUE THREAD

**Issue by dasu88** [tablacus/TablacusExplorerAddons#10]
Can increase the pluging for "inner favorite" ? Thank you

**Comment by tablacus** [comment]
I will try to consider it.
Best regards,

**Comment by tablacus** [comment]
I've made an add-on "Favorites".
This can change position to Inner bar.
![9](https://cloud.githubusercontent.com/assets/5156977/20038201/e288e0be-a472-11e6-8013-cff1eb3b7f29.png)
Best regards,

**Comment by dasu88** [comment]
it's great...^__^
Thank you very much, I like this software very much.
If there have more plug-in tutorial, it should be more perfect. (Because there are many plug-ins, I can not try to)
Sorry, my English is not good. I hope you understand what I mean.
thanks again.

**Comment by dasu88** [comment]
When my window is on the left,  click the "My Favorites button" on the right
and the result will open on the left ... 
Other inner functions can be opened in the lower pane ,even if it is not active ...

![2016-11-07_201850](https://cloud.githubusercontent.com/assets/23251263/20057773/6d03771c-a528-11e6-8d2d-21f4b59c4470.jpg)

**Comment by tablacus** [comment]
I've adjusted it on Favorites 1.01.
Best regards,

**Comment by dasu88** [comment]
Good fast efficiency, thank you
