### ISSUE TITLE
Incorrect details in "about:remember" list

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#111]
The icons and details of the following items in "about:remember" list are incorrect, compared with "History".

- Desktop
- C:\windows\fonts
- User profile system folder
- Libraries system folder
- Library
- ZIP file
- CAB file
- Clip folder

Please help to solve this problem. Thanks.

![illus](https://user-images.githubusercontent.com/34089121/60751498-94d92a80-9fe8-11e9-9504-e620ef57dda0.png)

**Comment by tablacus** [comment]
That seems a bit difficult.
Thank you,
