### ISSUE TITLE
Address bar can't toggle the Directory

### ISSUE THREAD

**Issue by dasu88** [tablacus/TablacusExplorerAddons#12]
Paste the path of the address column, press Enter, you can not toggle the directory ...
![2016-12-03_150853](https://cloud.githubusercontent.com/assets/23251263/20857551/be291e34-b96a-11e6-9a2e-82e13f857f80.jpg)

**Comment by tablacus** [comment]
It worked well in my PC.
Which address bar add-on do you use?
![3](https://cloud.githubusercontent.com/assets/5156977/20859325/07470818-b99f-11e6-8b99-d25411259c14.png)
Best regards,

**Comment by dasu88** [comment]
Looks like my computer is the problem ... I re-download tablacus is correct
I re-plug the back, if there are problems and then give you feedback
