### ISSUE TITLE
Tree View show quick access

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [tablacus/TablacusExplorerAddons#120]
Would it be possible for the tree view add on to show quick access?

![image](https://user-images.githubusercontent.com/38865330/66263332-a0d6b300-e7b6-11e9-9b80-335d85b7890c.png)

**Comment by tablacus** [comment]
It exists only in frames.

Right click on the tab -> check "Show frames"

![image](https://user-images.githubusercontent.com/5156977/64609395-d1ba0700-d407-11e9-9d02-e5ff48200c95.png)

Regards,
