### ISSUE TITLE
search bar add on 1.02

### ISSUE THREAD

**Issue by dzjdfzjhdeh** [tablacus/TablacusExplorerAddons#13]
![fehler](https://cloud.githubusercontent.com/assets/24624060/21287954/100d3cdc-c477-11e6-9780-100b8db9a33d.jpg)

**Comment by tablacus** [comment]
I will adjust it on next version.

**Comment by tablacus** [comment]
I've adjusted it on Tablacus Explorer 16.12.20.
Best regards,

**Comment by dzjdfzjhdeh** [comment]
The error is eliminated. thank you. When I click on point 2 but still "everything" is displayed. I had searched for "test". Should not be synonymous only what to "test" appears?

I do not need the point 2. Can I deactivate this in the options?

best regards

**Comment by dzjdfzjhdeh** [comment]
Nicer I find the filter bar than the search bar. The filter bar does not include any subfolders. Pity that the point is not the filter bar as an option.

best regards

**Comment by tablacus** [comment]
> I do not need the point 2. Can I deactivate this in the options?
I've adjusted this on Tablacus Explorer 16.12.23.(Tree view 1.25)
Best regards,

**Comment by tablacus** [comment]
> I do not need the point 2. Can I deactivate this in the options?

I've adjusted this on Tablacus Explorer 16.12.23.(Tree view 1.25)
Best regards,

**Comment by dzjdfzjhdeh** [comment]
thank you very nice. If there was still a possibility to directly subfolders it would be perfect.

I have been looking for years for a windows explorer replacement. Now I have found him. Thank you very much.

**Comment by tablacus** [comment]
My pleasure.
