### ISSUE TITLE
Feature Request shortcut key for tabgroups

### ISSUE THREAD

**Issue by imtrobin** [tablacus/TablacusExplorerAddons#132]
Hi, I like to be able switch between tabgroups via keyboard.

**Comment by tablacus** [comment]
Please try the following scripts.

- [Switch tabgroups previous](https://gist.github.com/tablacus/3c928252949da4f102dc9d9c1c613aaf)

- [Switch tab groups next](https://gist.github.com/tablacus/57a3eec780bab6bb6cf58861c375afe3)

Regards,

**Comment by imtrobin** [comment]
Thanks!
