### ISSUE TITLE
Dark mode not working in Windows 10

### ISSUE THREAD

**Issue by kedema** [tablacus/TablacusExplorerAddons#133]
Hi, it seem the dark mode don't work in Windows 10, it work at the 1st activation of the addon but if you close and reopen tablacus only the "exlporer" stay in dark and all others things back to normal design.

Look like this after reopenning tablacus:
![image](https://user-images.githubusercontent.com/57567941/74815714-0953a600-52fa-11ea-92a7-211609d177f8.png)

**Comment by flier268** [comment]
You need to install 'darkmodes'

**Comment by kedema** [comment]
Indeed, I tried this new version and it works well! Thank you for your help!
