### ISSUE TITLE
Run at setup - TypeError when TE starts up

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#136]
![20200416_104345](https://user-images.githubusercontent.com/34089121/79410225-5b4f3a00-7fd2-11ea-93c6-b9b483dade40.png)
A TypeError occurs when TE starts up, if “Type” option of this add-on is JScript, Exec, RunAs and Add-ons.
![20200416_104424](https://user-images.githubusercontent.com/34089121/79410222-59857680-7fd2-11ea-90f9-dbd65be0290d.png)

**Comment by tablacus** [comment]
I have fixed it on Tablacus Explorer 20.4.16.
Give it a try.
Thank you,

**Comment by ccfs** [comment]
Tested OK. Thanks.
