### ISSUE TITLE
Count bar - unexpectedly becomes blank when and after a menu shows

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#137]
![1](https://user-images.githubusercontent.com/34089121/79410543-4f17ac80-7fd3-11ea-83ba-7d3331965920.png)
Show a menu (click menu menu / context menu by right-click)
The count disappears.
![2](https://user-images.githubusercontent.com/34089121/79410548-517a0680-7fd3-11ea-9ea6-2f6b2c4d3594.jpg)
The count still disappears after the menu is dismissed.
![3](https://user-images.githubusercontent.com/34089121/79410552-5343ca00-7fd3-11ea-951d-b04558c745a9.png)

**Comment by tablacus** [comment]
I have fixed it on Count bar 1.08.
Please try it out.
Thank you,

**Comment by ccfs** [comment]
Tested OK. Thanks.
