### ISSUE TITLE
Tab plus - tab name not updated after context command on inactive tab

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#138]
When a context command is used on an inactive tab, a new name is not displayed until the user switches the active tab. Such commands include:
- Navigation commands
- Go home add-on
- Name the Tab add-on

Example:

1. M drive is in an INACTIVE tab
![1](https://user-images.githubusercontent.com/34089121/79410937-36f45d00-7fd4-11ea-8838-1531f5876428.png)
2. Right click M drive tab and choose "Change tab name"
![2](https://user-images.githubusercontent.com/34089121/79410949-3bb91100-7fd4-11ea-9e2e-ad3be11a9e6a.jpg)
3. Enter a new tab name
![3](https://user-images.githubusercontent.com/34089121/79410964-42e01f00-7fd4-11ea-8864-eeb7c9df5f3d.png)
4. The tab name is not updated
![4](https://user-images.githubusercontent.com/34089121/79410966-42e01f00-7fd4-11ea-8324-c65c066fcca2.png)
5. until a user switches tab
![5](https://user-images.githubusercontent.com/34089121/79410962-41aef200-7fd4-11ea-8a48-270d4d19737c.png)

**Comment by tablacus** [comment]
I have fixed it on Tab plus 1.54.
Please try it.
Thank you,

**Comment by ccfs** [comment]
Tested OK. Thanks.
