### ISSUE TITLE
Tab position - group favorite item incorrectly opens in reversed order

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#139]
If “New tab” is set to “Last”, and a group favorite item (Open in background) is opened, the tabs are incorrectly opened in reversed order. Example:

![0](https://user-images.githubusercontent.com/34089121/79412068-1ed20d00-7fd7-11ea-9cad-fa78dc90cbb8.png)
![0 fav c](https://user-images.githubusercontent.com/34089121/79412151-59d44080-7fd7-11ea-8305-a923da899181.png)
![2c failed](https://user-images.githubusercontent.com/34089121/79412200-7a9c9600-7fd7-11ea-94ad-f3c1e67e84c3.png)
Note that there is no such problem if "Type" is "Open" or "Open in new tab".

**Comment by tablacus** [comment]
I have adjusted it on Tablacus Explorer 20.4.16.
Please try it.
Thank you,

**Comment by ccfs** [comment]
Although the new version solves the sequence problem above, "Last" option of "New tab" of the add-on does not work now, for any method of creating a new tab. Example:
![1](https://user-images.githubusercontent.com/34089121/79563359-40b6b700-80df-11ea-8128-156866f1337b.png)
Open the group favorite item
![2](https://user-images.githubusercontent.com/34089121/79563362-42807a80-80df-11ea-829d-f8b8b709e761.png)

**Comment by ccfs** [comment]
The problem is solved in the new version of the add-on. Thanks.
