### ISSUE TITLE
Add "Progress Bar" for wfx plugins for get/put operations

### ISSUE THREAD

**Issue by Kranf99** [tablacus/TablacusExplorerAddons#14]
I am developing a wfx plugin to access the files inside a HDFS cluster.
The wfx plugin is 100% c code developped with VS2008 (thus very small: less than 200KB).
I love "Tablacus Explorer" because it's very compact, very beautiful and very customizable.

My wfx plugin is ***nearly*** working OK inside "Tablacus Explorer": i.e. The only things that needs improvement is the "file copy" operation (between HDFS and the local File System). i.e. When I copy large file like this (1.7 GB):
![2017-01-22_194036](https://cloud.githubusercontent.com/assets/20713234/22184858/af98655e-e0da-11e6-8540-194eb5a1a919.png)
...the interface "freezes" for a very long time. That's not ok. 
Instead, I'd like to have something like:
![2017-01-22_193513](https://cloud.githubusercontent.com/assets/20713234/22184871/d3d45126-e0da-11e6-9e72-6976a6396ff6.png)
...which is ok.

Can you display a "progress bar" inside "Tablacus Explorer" (it's important when copying large files between HDFS and the local File System).
Thanks a lot for your help!
Frank

**Comment by tablacus** [comment]
I will give it a try.
Thank you,

**Comment by Kranf99** [comment]
That's great! 
      See you!
      Frank
      
      
      ---- Original Message ---
      Subject: Re: [tablacus/TablacusExplorerAddons] Add "Progress Bar"
      for wfx plugins for get/put operations (#14)
      Date: Mon, 23 Jan 2017 05:05:40 -0800
      To: Tablacus/tablacusexploreraddons,Frank Vanden Berghen, Author
      From: Gaku
      
         
    
    
    
      I will give it a try.
        Thank you,
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tablacus/TablacusExplorerAddons","title":"tablacus/TablacusExplorerAddons","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tablacus/TablacusExplorerAddons"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tablacus in #14: I will give it a try.\r\nThank you,"}],"action":{"name":"View Issue","url":"https://github.com/tablacus/TablacusExplorerAddons/issues/14#issuecomment-274483061"}}}
    
    
      ===============================
Dr. Ir. Frank Vanden Berghen
Avenue Auguste Rodin, 20 bt 26
B-1050 Brussels - Belgium
Phone: + 32 479 - 992768
email: frank@applied-mathematics.net
web: http://www.applied-mathematics.net

**Comment by tablacus** [comment]
It corresponds to the progress dialog with wfx addon 1.04.
Best regards,

**Comment by Kranf99** [comment]
Thanks a lot for that!  
      it's working great! 
      
      I just tested now: I find it nice that you display the progress
      bar only for the really bug files (that are taking more than 5
      seconds to get/put).
      
      While it's busy copying the (large) file(s) in one "Tablacus
      window", I'd like to open another "Tablacus Process" to continue
      working on other files. Currently, I can only have one Tablacus
      Window and never two. Is there an add-on to allow more than one
      Tablacus Window?
      
      Again: Thanks already a lot for your work! It's wonderful! 
      
      See you!
      Frank
      
      
      ---- Original Message ---
      Subject: Re: [tablacus/TablacusExplorerAddons] Add "Progress Bar"
      for wfx plugins for get/put operations (#14)
      Date: Thu, 26 Jan 2017 06:45:32 -0800
      To: Tablacus/tablacusexploreraddons,Frank Vanden Berghen, Author
      From: Gaku
      
         
    
    
    
      It corresponds to the progress dialog with wfx addon 1.04.
        Best regards,
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tablacus/TablacusExplorerAddons","title":"tablacus/TablacusExplorerAddons","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tablacus/TablacusExplorerAddons"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tablacus in #14: It corresponds to the progress dialog with wfx addon 1.04.\r\nBest regards,"}],"action":{"name":"View Issue","url":"https://github.com/tablacus/TablacusExplorerAddons/issues/14#issuecomment-275405211"}}}
    
    
      ===============================
Dr. Ir. Frank Vanden Berghen
Avenue Auguste Rodin, 20 bt 26
B-1050 Brussels - Belgium
Phone: + 32 479 - 992768
email: frank@applied-mathematics.net
web: http://www.applied-mathematics.net

**Comment by tablacus** [comment]
Please copy Tablacus Explorer in a different folder.
e.g.
c:\app\te
c:\app\te2

Best regards,

**Comment by Kranf99** [comment]
Ok. Great! ^^

I'll now finish the wfx plugin and send it to you.

Also: I am currently developing a "big data" solution ([Anatella](http://www.anatella.com)) and I'll directly include Tablacus Explorer inside the standard [Anatella](http://www.anatella.com) distribution, (to provide direct&easy access to HDFS using using TE): That should give you some more visibility: You really deserve it.

See you!
