### ISSUE TITLE
regarding add-on virtualnames

### ISSUE THREAD

**Issue by rzw** [tablacus/TablacusExplorerAddons#143]
I can assign a persistant name to folders and files. But now what?
I would assume this is for
1. navigating to
2. filtering and searching by

or not?

**Comment by tablacus** [comment]
Example
1. Navigating to `C:\bin`
2. Filtering by `*.txt`


`C:\bin\*.txt`

![image](https://user-images.githubusercontent.com/5156977/80215048-c8b83600-8676-11ea-9d19-b505f3e635d3.png)


Regards,

**Comment by tablacus** [comment]
You can only see the virtual name. Please use your real name for filtering, etc.

**Comment by rzw** [comment]
Thanks. Good to know.
