### ISSUE TITLE
regarding add-on Label

### ISSUE THREAD

**Issue by rzw** [tablacus/TablacusExplorerAddons#144]
Assigning, filtering/searching by label works great. But is there a way to see the labels in one of the columns? Or is it only file by file?

**Comment by tablacus** [comment]
You can see the label in the label column.
![image](https://user-images.githubusercontent.com/5156977/80227827-2b1a3200-8689-11ea-9ea6-6273a5a378f0.png)

Right click on the item -> Label -> Details to open "Label" column.
![image](https://user-images.githubusercontent.com/5156977/80228192-ad0a5b00-8689-11ea-8de4-54c18918ac30.png)

Regards,

**Comment by rzw** [comment]
Thanks for the quick response. Actually, what you say is what I remembered. I updated yesterday. I only have 5 items in the menu:

![image](https://user-images.githubusercontent.com/1249327/80239269-37d66000-8660-11ea-9a68-b11fda66812f.png)

**Comment by rzw** [comment]
Also, I selected Label (or Bezeichnung) after clicking on the column-headers. But the column is empty. No labels from Tablacus Explorer.

**Comment by tablacus** [comment]
Please uncheck Options -> List-> Explorer Browser -> Details

![image](https://user-images.githubusercontent.com/5156977/80260258-6f75f400-86c2-11ea-995f-e7980b6fc8c9.png)

Many add-ons do not work with "Explorer Browser" checked.

Regards,

**Comment by rzw** [comment]
Thank you very much. You are very right.

I guess this setting is stored in windows.xml because deleting this file helped as well. The program rebuilds it.
