### ISSUE TITLE
Mixed sort & Total file size sort - Sorting sequence not used upon auto refresh

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#146]
Please help to solve the problem in 2 add-ons.

Recent versions of TE can automatically refresh a file list according to the current sorting sequence when there is a new item (or when an item is renamed). However the sequence is not used if the file list is using “Mixed sort” or "Total file size sort".

**_“Mixed sort” case:_**
Sort a folder with "mixed sort" name sequence
![2](https://user-images.githubusercontent.com/34089121/80473008-1b943500-8978-11ea-8235-e55e0da95e2c.jpg)
Then copy an item here
![4](https://user-images.githubusercontent.com/34089121/80473017-1d5df880-8978-11ea-9445-9531fe26328f.jpg)
The file list is now sorted by name with folders separately on top, not in "mixed sort" name sequence.
![5](https://user-images.githubusercontent.com/34089121/80473021-1df68f00-8978-11ea-894a-33da2c4f1260.png)

_**"Total file size sort" case:**_
Sort a folder with "total file size sort"
![2](https://user-images.githubusercontent.com/34089121/80472856-e12a9800-8977-11ea-9d5e-68065c7fe8ff.jpg)
Then copy an item here
![4](https://user-images.githubusercontent.com/34089121/80472858-e1c32e80-8977-11ea-8571-b0494f13bfad.jpg)
The file list is now sorted by name with folders separately on top, not in "Total file size sort" sequence.
![5](https://user-images.githubusercontent.com/34089121/80472849-df60d480-8977-11ea-9a66-674c7b706058.png)

**Comment by ccfs** [comment]
After a lot of tests, I find that:
- auto refresh just occurs in certain situations, and
- with either one of the add-ons, after auto refresh, the sort direction arrow in column heading disappears, which indicates that the file list is unsorted. This is not expected but can barely be considered correct.

Therefore I have enabled "Force refresh" add-on to make sure that any auto refresh will follow the current sorting sequence.

Regards,

**Comment by CollinChaffin** [comment]
Why was this closed? I just opened a new issue related, because now the total file size no longer never refreshes unless you go deeper into the structure, and back out, but now clicking sort by total file size column does absolutely nothing no matter how long I wait.

I haven't tried this other addon you mention "force refresh" but if installing/enabling this other addon is a requirement for file size sort to even work, perhaps they should be merged into one addon?
