### ISSUE TITLE
Force refresh - cannot detect a new folder

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#149]
I tried to use "force refresh" but the add-on could not detect a new folder as expected.
![0a](https://user-images.githubusercontent.com/34089121/81058706-9245ab00-8f01-11ea-8630-e80c92f2a1dc.png)
![0b](https://user-images.githubusercontent.com/34089121/81058714-94a80500-8f01-11ea-9b87-39a43be8da88.png)
![1a](https://user-images.githubusercontent.com/34089121/81058715-95409b80-8f01-11ea-98fb-c8ed6247d765.png)
![1b](https://user-images.githubusercontent.com/34089121/81058716-95409b80-8f01-11ea-8d4c-e2c0682644e5.png)
Please help to solve this problem. Thanks.

**Comment by I-Vladimir** [comment]
What is Filter and Disable items format on the Tabs tab? Just names as they appear on the tab or path with a mask?

**Comment by tablacus** [comment]
@ccfs I have adjusted it with Force refresh 1.03.

**Comment by tablacus** [comment]
@I-Vladimir 
Filter specifies [the wildcard path](https://github.com/tablacus/TablacusExplorer/wiki/filters-and-queries) that perform Force refresh.
On the other hand, Disable specifies the wildcard path that does not perform Force refresh.
Regards,

**Comment by ccfs** [comment]
The problem is solved with the new version. Thanks.
