### ISSUE TITLE
Side Tree View Error...

### ISSUE THREAD

**Issue by dasu88** [tablacus/TablacusExplorerAddons#16]
When I installed "Side Tree View" plug-in, after reopening to get this error message.. 
![2017-02-12_191850](https://cloud.githubusercontent.com/assets/23251263/22861632/bcb28ec0-f158-11e6-983d-beacc8d8deca.jpg)

Sorry, I tried to convert to English interface, but still get the Chinese error message, should be related to the operating system of the default language, it can not provide English error message ...

**Comment by tablacus** [comment]
Please update an add-on "Font settings".
Best regards,

**Comment by dasu88** [comment]
My "Font settings" is last version
So I tried to reinstall "Font settings" ，now its ok...
If you can provide the function to adjust the width of the layout, it should be more perfect

**Comment by tablacus** [comment]
I’ll give it a try.
Thank you,

**Comment by tablacus** [comment]
It has been completed on Tablacus Explorer 17.2.18 & Side tree view 1.01.
Please update them.
Best regards,

**Comment by dasu88** [comment]
Great, thank you

**Comment by tablacus** [comment]
My pleasure,
