### ISSUE TITLE
Quickly open menus - Default menu is not that one shows when this add-on is disabled

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#163]
When this add-on is enabled:
![enabled1](https://user-images.githubusercontent.com/34089121/82198192-8ceb5600-992e-11ea-985e-0886e6613d90.jpg)
![enabled2](https://user-images.githubusercontent.com/34089121/82198198-8f4db000-992e-11ea-97fb-ce1110726381.jpg)
When this add-on is disabled, the menu is different from the above.
![disabled](https://user-images.githubusercontent.com/34089121/82198236-9aa0db80-992e-11ea-8c2a-ead859a229db.jpg)

Please fix if this is a problem. Thanks.

**Comment by tablacus** [comment]
There seems to be no other way to get this context menu than by right-clicking on the tree view.
So, I think it's difficult to fix.

In the meantime, use the right click while holding down the Shift key.

Regards,

**Comment by ccfs** [comment]
This is just a bit inconsistency so it is OK not to fix.
Thanks for your advice.
