### ISSUE TITLE
Folder menu filter - 2 problems

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#166]
Please help to solve the problems. Thanks.

**Problem 1**
"Browse" button: The returned path is incorrect for a library item.
![20200522_115546](https://user-images.githubusercontent.com/34089121/82633301-5adb3c00-9c2d-11ea-8fa3-179ee9d8c624.png)
![20200522_115556](https://user-images.githubusercontent.com/34089121/82633308-5ca4ff80-9c2d-11ea-9767-ad6856ed6dff.png)
![20200522_115611](https://user-images.githubusercontent.com/34089121/82633310-5d3d9600-9c2d-11ea-803d-dd929027b356.png)

**Problem 2**
"Browse" button: If Shift key is pressed when Cancel button is clicked, the button incorrectly returns *
![20200522_115546](https://user-images.githubusercontent.com/34089121/82633330-69295800-9c2d-11ea-86d1-deabf5c92911.png)
![20200522_115806](https://user-images.githubusercontent.com/34089121/82633331-6a5a8500-9c2d-11ea-9908-4613c65fb0b2.png)
![20200522_115812](https://user-images.githubusercontent.com/34089121/82633332-6af31b80-9c2d-11ea-8f4a-f7b0385a75c0.png)

**Comment by ccfs** [comment]
With new version 1.01, problem 2 is solved. Problem 1 is still outstanding.
Regards,

**Comment by tablacus** [comment]
Problem 1
The return value from the dialog box is a string, so there's nothing I can do about it.

Regards,

**Comment by ccfs** [comment]
OK, I see it as a tiny limitation. I can use the Select button which can return a correct path, anyway. Thanks.
