### ISSUE TITLE
recently closed tabs not working?

### ISSUE THREAD

**Issue by dasu88** [tablacus/TablacusExplorerAddons#17]
Recently used this plugin : "recently closed tabs", it seems not working ...I  try to download a new file test, is the same ... Is there a problem?

**Comment by tablacus** [comment]
Have you installed an add-on "Undo close tab"?

![11](https://cloud.githubusercontent.com/assets/5156977/23747680/e855d9ba-0503-11e7-8187-1d4d9b8a1952.png)

Best regards,

**Comment by dasu88** [comment]
Really is the lack of this plug-in ... Thank you

**Comment by tablacus** [comment]
My pleasure.
