### ISSUE TITLE
Grab bar - show admin

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#175]
Please consider enhancing Grab bar so that it can display "admin" when TE is run with admin rights. Thanks.
![admin](https://user-images.githubusercontent.com/34089121/84257738-6775f480-ab48-11ea-995a-dda96dcd0c4a.png)

**Comment by ccfs** [comment]
This issue is solved with new version 1.07, but "drag to restore maximized window" does not work now.

Regards,

**Comment by tablacus** [comment]
It works fine for me.
Let me know your environment.(OS and ...)

Regards,

**Comment by ccfs** [comment]
Sorry it was a false alarm. I disabled that feature with a tweaking app.

Regards,
