### ISSUE TITLE
Fix selection on sort and update dir - not working

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#180]
The latest version 1.09 of the add-on does not work. Please help to solve this problem. Thanks.

Example:
Select 3 items
![20200624_094418](https://user-images.githubusercontent.com/34089121/85488583-229a9500-b601-11ea-949d-4e2b7648216e.png)
Deselect 1 item
![20200624_094425](https://user-images.githubusercontent.com/34089121/85488585-23332b80-b601-11ea-9476-e844e8fd1462.png)
Sort the file list. The deselected item incorrectly becomes selected.
![20200624_094437](https://user-images.githubusercontent.com/34089121/85488575-20d0d180-b601-11ea-8d8f-cb8dab566ee0.png)
This problem can be solved by previous versions but not the latest.

**Comment by ccfs** [comment]
The problem is solved when "Show frames" is disabled, but the problem occurs when "Show frames" is enabled.

![20200625_161343](https://user-images.githubusercontent.com/34089121/85684715-f36b4d00-b700-11ea-95c2-300a28eca465.png)
![20200625_161349](https://user-images.githubusercontent.com/34089121/85684720-f403e380-b700-11ea-917b-24a6977f3845.png)
![20200625_161357](https://user-images.githubusercontent.com/34089121/85684706-f108f300-b700-11ea-871d-40e26ad25653.png)

**Comment by ccfs** [comment]
The problem is solved with the new version 1.11. Thanks.

**Comment by ccfs** [comment]
Just found another problem:

Select one or more items
![20200627_185119](https://user-images.githubusercontent.com/34089121/85920646-04a28e00-b8a8-11ea-948e-49887a168f54.png)
then deselect all items one by one (hover on the item while keep Ctrl key pressed)
![20200627_185134](https://user-images.githubusercontent.com/34089121/85920650-066c5180-b8a8-11ea-89d7-4fcd07d181c5.png)
then sort the file list. The selection unexpectedly re-appears.
![20200627_185139](https://user-images.githubusercontent.com/34089121/85920651-0704e800-b8a8-11ea-9977-fb61dd200a99.png)

Please help to solve this problem. Thanks.

**Comment by tablacus** [comment]
I have adjusted it in Fix selection 1.13.

Thank you for everything.

**Comment by ccfs** [comment]
The problem is solved. Thanks.

**Comment by ccfs** [comment]
Last problem (27 Jun 2020) re-appears in the latest version 1.16. Please help to solve this. Thanks.

**Comment by ccfs** [comment]
The problem is solved by the new TE version 21.4.9. Thanks.
