### ISSUE TITLE
Hot key for Split

### ISSUE THREAD

**Issue by Hans470** [tablacus/TablacusExplorerAddons#182]
It would be nice if I can switch from normal view to the different split views with a configurable hot key. For example F3 to 2x1, F4 to 2x2 ...
Maybe this is possible with the Key add on. But how?
I tried to set a key for loading a layout like "layout\v2tabs.xml", but this removes all open tabs. 
How to get the same behaviour like with the buttons?

**Comment by Hans470** [comment]
I think I got it :-)
Just digging a little into the other issues and the javascript code.
Only switching it with the same button is not possible in this way, but I think I can live with that.
You just have to add following In Addons --> Key --> in Type "JScript":  

Addons.Split.Exec(1, 1); for normal view
Addons.Split.Exec(2, 2); for 1x2
Addons.Split.Exec(2, 3); for 2x1
Addons.Split.Exec(4, 4); for 2x2

![grafik](https://user-images.githubusercontent.com/67957916/88536031-56574900-d00b-11ea-83f8-8a2e23b6b1fc.png)

**Comment by tablacus** [comment]
Toggle 1x1 <-> 1x2
```
if (te.Ctrls(CTRL_TC, true).Count != 1) {
  Addons.Split.Exec(1, 1);
} else {
  Addons.Split.Exec(2, 2);
}
```

Toggle 1x1 <-> 2x1
```
if (te.Ctrls(CTRL_TC, true).Count != 1) {
  Addons.Split.Exec(1, 1);
} else {
  Addons.Split.Exec(2, 3);
}
```

Toggle 1x1 <-> 2x2
```
if (te.Ctrls(CTRL_TC, true).Count != 1) {
  Addons.Split.Exec(1, 1);
} else {
  Addons.Split.Exec(4, 4);
}
```

Regards,

**Comment by Hans470** [comment]
Absolutely great. Thank you!

**Comment by hansu** [comment]
Follow-up: https://github.com/tablacus/TablacusExplorerAddons/issues/390

**Comment by hansu** [comment]
Thanks! But this adds a new tab in the right pane and keeps the old one when splitting.
And what does the loop do?

**Comment by ccfs** [comment]
(1) The loop: If there is already a same tab in the right window, switch to the tab.
(2) Otherwise the current folder will be opened (duplicated) in the right window.

Don't you want the duplicated tab? Or you just want to MOVE the current tab to the right window?

**Comment by hansu** [comment]
>Don't you want the duplicated tab? Or you just want to MOVE the current tab to the right window?

I want the same tab duplicated/mirrored to the rigth pane, but I want this be the only tab in the right pane. 
But I found a solution for this. I just needed to set the option "close all tabs" in the split add on :)
And with or without the loop does not make any difference now.
