### ISSUE TITLE
Enhancement request: Tab position - new option for tab closing: Ascendant folder

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#187]
Currently "Parent folder" option helps to switch to a parent folder tab automatically. The new "Ascendant folder" option will be similar, but will search upwards in folder tree if the parent folder tab is not found.

Example:
![20200731_165420](https://user-images.githubusercontent.com/34089121/89024582-ec66d880-d357-11ea-8227-37861fbcf1d7.png)
Close "tab position" tab
![20200731_170141](https://user-images.githubusercontent.com/34089121/89024591-ee309c00-d357-11ea-9f8f-ed652753e761.png)
Since "addons" is not opened, TE switches to the tab at the right.
![20200731_170150](https://user-images.githubusercontent.com/34089121/89024592-eec93280-d357-11ea-8bf3-b53800239982.png)
With the new "Ascendant folder" option, TE will switch to "te200730" tab (after it fails to find "addons" tab).
In case "te200730" tab is again not found, TE will try "M:\", "Computer" and lastly "Desktop".

**Comment by tablacus** [comment]
I think this feature can be included in the "Parent folder".
Regards,

**Comment by ccfs** [comment]
I have tried the new version 1.06. TE stops working if a tab is closed (M:\) while its upper-level folders are not opened (Computer, Desktop).
![20200804_115725](https://user-images.githubusercontent.com/34089121/89259636-508de300-d65d-11ea-93f5-daa6a648b555.png)

Regards,

**Comment by ccfs** [comment]
The new version 1.07 is OK. Thanks.
