### ISSUE TITLE
Menu item filter - option to bypass its function

### ISSUE THREAD

**Issue by brgrvrm** [tablacus/TablacusExplorerAddons#195]
Is there any way to temporarily bypass the function of the Menu Item Filter add-on? I like to work with cleaned up menus, but sometimes you need all menu items. In normal explorer you can also activate an advanced context menu by holding the SHIFT key and RIGHT MOUSE BUTTON click. So is a way to use this function in TE?

**Comment by tablacus** [comment]
I have adjusted it on "Menu item filter 1.02".
Please try to update.

Regards,

**Comment by brgrvrm** [comment]
Works as expected.
