### ISSUE TITLE
Sort tabs - Result list tabs are unexpectedly in descending order

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#197]
File folder tabs are sorted by path in ascending order. However result list tabs are unexpectedly in descending order.

![20200829_131720](https://user-images.githubusercontent.com/34089121/91631180-5089c480-ea0a-11ea-9b59-c942831ae7e9.png)
![20200829_131656](https://user-images.githubusercontent.com/34089121/91631182-51baf180-ea0a-11ea-94d6-f0f06a7c3231.png)

Please check if this can be solved. Thanks.

**Comment by tablacus** [comment]
I have not encountered this issue.
![image](https://user-images.githubusercontent.com/5156977/91637106-db85b180-ea40-11ea-81e7-ad6c8d661b9c.png)
![image](https://user-images.githubusercontent.com/5156977/91637096-c6a91e00-ea40-11ea-940c-ee8c6857c8c3.png)

Regards,

**Comment by ccfs** [comment]
The problem occurs in TE64, not in TE32.

Regards,

**Comment by ccfs** [comment]
The problem is solved in TE 20.8.30. Thanks.
