### ISSUE TITLE
Why this number appears？？

### ISSUE THREAD

**Issue by dasu88** [tablacus/TablacusExplorerAddons#20]
![2017-08-19_221329](https://user-images.githubusercontent.com/23251263/29487499-b53a663c-852c-11e7-80b5-eaba441e2807.jpg)

I installed  add favorites plug-in, the figure shows a number on the right (24), I do not know what that means?

**Comment by tablacus** [comment]
Add to Favorites 1.02 released.
Please try update it.

Thank you,
