### ISSUE TITLE
wiki images

### ISSUE THREAD

**Issue by tablacus** [tablacus/TablacusExplorerAddons#21]
Address bar
![image](https://user-images.githubusercontent.com/5156977/31580281-c41a51dc-b185-11e7-8df4-4ef0c9cd1434.png)
Address bar (Breadcrumbs style)
![image](https://user-images.githubusercontent.com/5156977/31580108-693a433e-b181-11e7-9cbd-8f210fd54898.png)
Address bar (XP style)
![image](https://user-images.githubusercontent.com/5156977/31580130-015b921c-b182-11e7-8159-9f1d2582e9f8.png)

**Comment by tablacus** [comment]
Back
![image](https://user-images.githubusercontent.com/5156977/31580324-0e9fc61e-b187-11e7-89a8-a63dd4fe35b5.png)

**Comment by tablacus** [comment]
Extract
![image](https://user-images.githubusercontent.com/5156977/31580578-370e1daa-b18f-11e7-8891-0b0b2459c68a.png)

**Comment by tablacus** [comment]
Filter
![image](https://user-images.githubusercontent.com/5156977/31580631-cdc614ae-b190-11e7-90ce-a4a21d9cf31f.png)

**Comment by tablacus** [comment]
Forward
![image](https://user-images.githubusercontent.com/5156977/31580671-f54c7f1c-b191-11e7-80cf-4c0ca6830ccd.png)

**Comment by tablacus** [comment]
Key
![image](https://user-images.githubusercontent.com/5156977/31580716-0ce34718-b193-11e7-99e6-96a322492e1b.png)

**Comment by tablacus** [comment]
Main Menu
![image](https://user-images.githubusercontent.com/5156977/31580725-6b127a02-b193-11e7-9f9e-a41326173639.png)

**Comment by tablacus** [comment]
Mouse
![image](https://user-images.githubusercontent.com/5156977/31580745-22bcb2da-b194-11e7-8c42-b283d2171ca5.png)

**Comment by tablacus** [comment]
Tree view
![image](https://user-images.githubusercontent.com/5156977/31580778-baed7670-b194-11e7-8855-a13b172c082c.png)

**Comment by tablacus** [comment]
Tabs
![image](https://user-images.githubusercontent.com/5156977/31580800-44fe1bc6-b195-11e7-8cee-8f5adc6eb481.png)

**Comment by tablacus** [comment]
Title bar
![image](https://user-images.githubusercontent.com/5156977/31580811-988a9102-b195-11e7-8af8-612830a67398.png)

**Comment by tablacus** [comment]
Tool bar
![image](https://user-images.githubusercontent.com/5156977/31580822-dc20bbe4-b195-11e7-8e94-57b405abc088.png)

**Comment by tablacus** [comment]
Up
![image](https://user-images.githubusercontent.com/5156977/31580838-1a3870c0-b196-11e7-9d09-40818a72efca.png)

**Comment by tablacus** [comment]
Tab plus
![image](https://user-images.githubusercontent.com/5156977/31663095-dd0f8e08-b37b-11e7-8700-affe931c1bce.png)

Options
![image](https://user-images.githubusercontent.com/5156977/31663185-1ef64c6c-b37c-11e7-98ac-916a010d83b9.png)

**Comment by tablacus** [comment]
Badge
![image](https://user-images.githubusercontent.com/5156977/31663614-a4ae0f24-b37d-11e7-8c76-80a3d4be138e.png)
![image](https://user-images.githubusercontent.com/5156977/31663637-bc53ae18-b37d-11e7-9f49-fcf7dff36641.png)

**Comment by tablacus** [comment]
Tab groups
![image](https://user-images.githubusercontent.com/5156977/33073369-0eb7437e-cf06-11e7-93da-71e5c2451ce3.png)

**Comment by tablacus** [comment]
Remember folder view settings
![image](https://user-images.githubusercontent.com/5156977/33267568-505fe414-d3bd-11e7-9da6-de3e8bd5dbb0.png)

**Comment by tablacus** [comment]
Stripes lite
![image](https://user-images.githubusercontent.com/5156977/33268647-59d3415e-d3c1-11e7-9044-91074e2e01ec.png)
No emphasis
![image](https://user-images.githubusercontent.com/5156977/33268703-88f35cb2-d3c1-11e7-93ef-0b5504235292.png)

**Comment by tablacus** [comment]
Gridlines
![Gridlines](https://user-images.githubusercontent.com/5156977/33269533-6a1174fc-d3c4-11e7-9983-c3c4dc26e709.png)

**Comment by tablacus** [comment]
Stripes
![image](https://user-images.githubusercontent.com/5156977/34878040-fc6816ee-f7eb-11e7-93a5-50f16dff448c.png)

**Comment by tablacus** [comment]
Classic Style
![image](https://user-images.githubusercontent.com/5156977/34878182-a07db018-f7ec-11e7-8812-9a9cd0d8885b.png)

**Comment by tablacus** [comment]
GFL SDK
![image](https://user-images.githubusercontent.com/5156977/35806047-7cc71e2e-0ac1-11e8-94e0-b4d1207affc8.png)
Download
![image](https://user-images.githubusercontent.com/5156977/35806070-96fd21a8-0ac1-11e8-8958-b9855241cec6.png)

**Comment by duttyend** [comment]
Thank you so much for making the BEST file explorer/manager I have ever used !!!

And thanks a lot for the detailed information and images to better understand every awesome add-on !

Have a great day
