### ISSUE TITLE
ReName file not working

### ISSUE THREAD

**Issue by OldCityCat** [tablacus/TablacusExplorerAddons#22]
Running Windows 10 Pro with all the latest updates
Tablacus Info
![image-0021](https://user-images.githubusercontent.com/32240880/35938624-a9621d9c-0c17-11e8-97fa-f84287203575.png)

Selected file pressed F2 to edit tried appending the "Old".to file name.
![image-0022](https://user-images.githubusercontent.com/32240880/35938696-ee111f24-0c17-11e8-89fd-69203cfdde4e.png)

![image-0024](https://user-images.githubusercontent.com/32240880/35938835-64bbcfb6-0c18-11e8-95f5-6f3318aec820.png)
Press enter reverts back to original file name.
Also tried using right mouse menu with same results
Installed ReName Dialog Box  Add-On  
Selected file Pressed F2 get this popup
![image-0025](https://user-images.githubusercontent.com/32240880/35939192-63df171e-0c19-11e8-8751-161e82a19723.png)
Rename didn't work here either.

**Comment by tablacus** [comment]
I haven't encountered this.
Couldn't you also rename other files?

Thank you,

**Comment by ccfs** [comment]
I found a new add-on named "Fix selection on renaming" released on 2018/2/14. It seems to fix the above problem, but it does not work:
- “Find Files” result list: a renamed file is still shown with the old name
- “Everything” result list: a renamed file disappears from the list

**Comment by tablacus** [comment]
It's in the specifications.
These Results folders are not updated automatically.
Please update manually.

Thank you,
