### ISSUE TITLE
[Improvement] "Check for update" add-on

### ISSUE THREAD

**Issue by duttyend** [tablacus/TablacusExplorerAddons#24]
Dear @tablacus , 
I think it would be great to have an add-on to automatically check for updates of Tablacus and of add-ons themselves.
For example, at Tablacus launch, or at a given periodicity (every 1 day, every week, etc.).

What do you think about this ?

Thank you very much and have a great day !

**Comment by tablacus** [comment]
Hello, duttyend.
I will try to do with an add-on about it.

Thank you,

**Comment by duttyend** [comment]
Thank you so much and for replying so quickly !

**Comment by tablacus** [comment]
I've made add-ons "Auto update" and "Add-ons updater".
Please try to install these add-ons.

Best regards,

**Comment by duttyend** [comment]
That's awesome, thank you very much !

I have installed the "Auto update 1.00" add-on and checked the "Auto" box but it doesn't do anything for the moment. Is there something else to set up ?

**Comment by tablacus** [comment]
![image](https://user-images.githubusercontent.com/5156977/37063469-d00f8774-21dc-11e8-8c3e-cae56fbf5561.png)
- Day
Check for updates again later(Day)
Default: Once in 1 day.
Minimum: 1 day

- Background
Check for updates in idle state(Minute or hour)
Default: 10 minutes in idle state.
Minimum: 1 minute

- Auto
Omit confirmation dialog

**Comment by tablacus** [comment]
**Add-ons updater**

If you want to check for add-ons updates immediately:

- Help(H) -> Check for update

Check for updates of add-ons together with Tablacus Explorer.

Best regards,

**Comment by duttyend** [comment]
Thank you so much @tablacus !!!
