### ISSUE TITLE
Label SQLite3 - Not working

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#242]
Please help to solve the problem. Thanks.

I tried to set up the add-on but failed with a script error.
![1](https://user-images.githubusercontent.com/34089121/110892925-ee523a80-832f-11eb-8225-c5979cedea4f.png)
![2](https://user-images.githubusercontent.com/34089121/110892928-ef836780-832f-11eb-94c8-1a2c2b18550b.png)
![3](https://user-images.githubusercontent.com/34089121/110893123-5acd3980-8330-11eb-9aee-e422879f0b7f.png)
![4](https://user-images.githubusercontent.com/34089121/110892929-f01bfe00-832f-11eb-8bde-8bc2b553b6bf.png)
![5](https://user-images.githubusercontent.com/34089121/110892930-f01bfe00-832f-11eb-912f-46b58aa8c978.png)

**Comment by ccfs** [comment]
The new version works properly, except that when the Options page is opened, Information does not show.

![INFO](https://user-images.githubusercontent.com/34089121/111028017-c990bc80-842e-11eb-8781-d20a07844c14.png)

**Comment by ccfs** [comment]
Please spend some time to repair this add-on. Thanks.

**Comment by tablacus** [comment]
I have not encountered it.
![image](https://user-images.githubusercontent.com/5156977/114554429-ad887100-9ca1-11eb-9e29-d8a004ddc77a.png)

It will not be checked for incorrect dll such as 32-bit dll.
Please confirm dll.

Regards,

**Comment by ccfs** [comment]
The problem is not at the time the DLL path is entered.

The problem occurs if:
- the DLL path has been entered
- click OK to close the Options page
- OPEN the Options page AGAIN

Regards,

**Comment by ccfs** [comment]
The problem is solved by the new version. Thanks.
