### ISSUE TITLE
Restore tabs on start

### ISSUE THREAD

**Issue by nkay08** [tablacus/TablacusExplorerAddons#25]
This is not so much an issue in that it doesn't work. It does work pretty good and opens with all the tabs that were open the last time you closed tablacus.

However, I couldn't find any setting to turn it off. Often I want to have a fresh, clean workspace when opening the application. Maybe I have simply missed something in the files...

**Comment by tablacus** [comment]
1. Please install an add-on "Startup settings".
2. Open "Startup settings" options.
3. Choose Type to Tabs
4. Click on "Reference..." and choose "Close other tabs"

Type
`Tabs`
Options
`Close other tabs`

![image](https://user-images.githubusercontent.com/5156977/37091648-468d821a-224c-11e8-8e55-399568956ec0.png)

Best regards,

**Comment by nkay08** [comment]
Thank you very much!

**Comment by tablacus** [comment]
Ok, how about this command line.

`te64.exe "c:\program files" "tabs,Close other tabs"`

It opens "c:\program files".

bat file (te.bat) for te64.exe
```
@echo off
start te64.exe %1 "tabs,Close other tabs" %2 %3 %4 %5 %6 %7 %8
```
bat file (te.bat) for te32.exe
```
@echo off
start te32.exe %1 "tabs,Close other tabs" %2 %3 %4 %5 %6 %7 %8
```

Add-ons "Startup settings" is unnecessary.

Best regards,

**Comment by nkay08** [comment]
Thank you again. this is a nice  way of doing it. 
I only had a problem, that the console would say "Can not find te64.exe" when launching the bat. My guess was, that the bat somehow was executed in a different path where no te64.exe is. Other than hardcoding the path to the .exe this is a solution I found:
```
@echo off 
pushd %~dp0
start te64.exe %1 "tabs,Close other tabs" %2 %3 %4 %5 %6 %7 %8
```

And btw. I am using this registry file to set tablacus as my default file explorer and it works very good:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Folder\shell]
@="0Tablacus"

[HKEY_CLASSES_ROOT\Folder\shell\0Tablacus]
@="Open with Tablacus"

[HKEY_CLASSES_ROOT\Folder\shell\0Tablacus\command]
@="\"E:\\Programme\\Tablacus\\te64notabs.bat\" \"%1\""

[HKEY_CLASSES_ROOT\Directory\shell]
@="0Tablacus"

[HKEY_CLASSES_ROOT\Directory\shell\0Tablacus]
@="Open with Tablacus"

[HKEY_CLASSES_ROOT\Directory\shell\0Tablacus\command]
@="\"E:\\Programme\\Tablacus\\te64notabs.bat\" \"%1\""


[HKEY_CLASSES_ROOT\Drive\shell]
@="0Tablacus"

[HKEY_CLASSES_ROOT\Drive\shell\0Tablacus]
@="Open with Tablacus"

[HKEY_CLASSES_ROOT\Drive\shell\0Tablacus\command]
@="\"E:\\Programme\\Tablacus\\te64notabs.bat\" \"%1\""
```

**Comment by nkay08** [comment]
And as an addition to that, I found a way to run the .bat invisibly with the help of a .vbs

The te64notabs.vbs : 
```
Set WshShell = CreateObject("WScript.Shell") 
WshShell.Run """te64notabs.bat"" """ & WScript.Arguments.Item(0) &"""" 
Set WshShell = Nothing
```

And the new registry: 
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Folder\shell]
@="0Tablacus"

[HKEY_CLASSES_ROOT\Folder\shell\0Tablacus]
@="Open with Tablacus"

[HKEY_CLASSES_ROOT\Folder\shell\0Tablacus\command]
@="\"%windir%\system32\wscript.exe\" \"E:\\Programme\\Tablacus\\te64notabs.vbs\" \"%1\""

[HKEY_CLASSES_ROOT\Directory\shell]
@="0Tablacus"

[HKEY_CLASSES_ROOT\Directory\shell\0Tablacus]
@="Open with Tablacus"

[HKEY_CLASSES_ROOT\Directory\shell\0Tablacus\command]
@="\"%windir%\system32\wscript.exe\" \"E:\\Programme\\Tablacus\\te64notabs.vbs\" \"%1\""


[HKEY_CLASSES_ROOT\Drive\shell]
@="0Tablacus"

[HKEY_CLASSES_ROOT\Drive\shell\0Tablacus]
@="Open with Tablacus"

[HKEY_CLASSES_ROOT\Drive\shell\0Tablacus\command]
@="\"%windir%\system32\wscript.exe\" \"E:\\Programme\\Tablacus\\te64notabs.vbs\" \"%1\""
```

**Comment by nkay08** [comment]
And another improvement, since with the bat tablacus would always close all other tabs when opened, even if tablacus was already running:

```
@echo off
pushd %~dp0
tasklist /FI "IMAGENAME eq te64.exe" 2>NUL | find /I /N "te64.exe">NUL
if "%ERRORLEVEL%"=="0" (
start te64.exe %1 %2 %3 %4 %5 %6 %7 %8
) else (
start te64.exe %1 "tabs,Close other tabs" %2 %3 %4 %5 %6 %7 %8
)
```
