### ISSUE TITLE
Longer delay when switching tabs in newer versions of Tablacus with Tab Plus addon

### ISSUE THREAD

**Issue by InvisibleManX** [tablacus/TablacusExplorerAddons#274]
Hello. 

My OS is Windows 7 64 bit. 
I use a couple of HDD (old 1 TB ones).

I've been using the old version of Tablacus:  **20.9.3 with Tab Plus v1.61**
Before trying a new one I backed it up (so that I won't lose the old supported addon's versions).

I downloaded the most recent version: **21.4.22 with Tab Plus v1.80** 

There's a noticeable delay now, when switching from one tab to another, before that tab actually gains focus. 
**I compared it with v20.9.3 and Tab Plus v1.61** because I can run them from separate folders. 
And I used the same sets of tabs leading to same places on both HDDs.

The slight delay is present even in the older version, but it isn't big. And doesn't affect anything.
In v21.4.22 though, the delay is a lot longer, by comparison. 

And it creates a lot of annoyance when trying to quickly copy with Ctrl+C and then switching to another tab and pasting with Ctrl+V some files. 

When I do it quickly in v20.9.3 I always end up copying a file, even if I do it within 1/3 of a second after switching the tab. 

When I do it quickly (muscle memory) in v21.4.22 nothing happens, so I have to repeat my actions. (Or I have to wait for more than half a second after switching to each tab, on purpose. That's been kinda frustrating. )

You can notice the longer delay visually, if you highlight some file in one tab and other tab, and switch between them, waiting for a second between each switch. You'll see that the highlighting and focus is restored noticeably quicker on the old version of the addon.

**The problem is with Tab Plus v1.80** (It might be only relevant to Windows 7, but I have no way to test it).

I tried copying the older addon into Tablacus v21.4.22, forcing it to work with Tab Plus v1.61 and the delay is shorter again, just like it always was! (And if I update the addon, and then close and open Tablacus again, the delay is back.)

I understand that it won't make a difference for people who don't use keys to quickly copy / paste files, but for people like me, the newer version is unusable. 

Is it possible to solve this, or the newer versions are changed so much that the longer delay is impossible to technically remove from switching tabs?

**Comment by InvisibleManX** [comment]
I also should add, that it could be due to me having an old 2 core CPU, while on very fast modern ones, that delay might not exist at all. 

But, hopefully, the reason isn't just that the program requires more powerful computer now. 

Besides, it's just switching one tab. There's no need for almost any delay at all, to just set focus. If I switch between two windows in Windows Explorer, they get in focus immediatelly, without even that slight delay that was noticeable even on the older version, so this much longer delay shouldn't even be there. I suspect that some optimization would reduce the delay to previous tolerable levels again.

**Comment by tablacus** [comment]
Please try to update "Tab plus 1.82".

Regards,

**Comment by InvisibleManX** [comment]
@tablacus 
> 
> 
> Please try to update "Tab plus 1.82".
> 

Wow! It's perfect now, and it updates even faster than it was on that older version, too! 

Thank you! 

I wonder what was that cause. 

By the way, I also tested the addons Up / Back / Forward. 

In the "Up" everything works just as fast. 

But in "Back" and "Forward" there's the same long delay after hitting those buttons, as it was on the Tab Plus v1.80 
I suspect that the similar solution you used for Tab Plus would make those work perfect as well.
