### ISSUE TITLE
Save selected items - nonexistent and invisible items

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#278]
Example

Select some items and save the selection
![1](https://user-images.githubusercontent.com/34089121/116851241-a0b5c800-ac24-11eb-85bf-a0371659eba7.png)
After some items are renamed / set to hidden / filtered out
![2](https://user-images.githubusercontent.com/34089121/116851448-f1c5bc00-ac24-11eb-9289-f0728576d5db.png)
Such items may or may not appear in the menu.

The menu should be better to list ALL items originally saved, but those nonexistent (renamed / moved / deleted) and invisible (hidden / filtered out) items are shown as DISABLED. This will let the user be aware of the discrepancy.

Regards,

**Comment by tablacus** [comment]
Maybe it will be very heavy if there are many items.

Regards,

**Comment by ccfs** [comment]
It is OK to leave the add-on as is if you have concern.

**Comment by ccfs** [comment]
With the new version, invisible items are now excluded from the menu. This is better. Thanks.
