### ISSUE TITLE
[Feature request] Paste as link

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#288]
This suggested new add-on will help users to create "symbolic links" and "junctions".

**Steps to use**

1. Copy one or more items to clipboard
2. Switch to destination folder
3. Click a (new add-on) button and choose from a menu:
- Symbolic link, absolute path
- Symbolic link, absolute path without drive
- Symbolic link, relative path
- Junction
4. TE must have started with admin privilege. Otherwise escalate the privilege to admin for link creation. (In the case the user replies No to escalation, abort.)
5. The add-on creates the link(s) in destination folder.

Do not show the menu if:
- Clipboard is empty
- Current (destination) folder is NOT in NTFS

**Creation of symbolic link**

Source item type:
- Folder: equivalent to MKLINK /D Link Target
- File: equivalent to MKLINK Link Target
- Any others (e.g. system folder, folder in a ZIP file, query): skip

If the source item is a network share, absolute path will be used, regardless of the menu option chosen.

If "relative path" is chosen, the add-on will determine the relative path by comparing the source with the destination.

_[May 28 added]_ If the source and the destination are on different drives, and the chosen option is:
- absolute path without drive: skip the item
- relative path: use absolute path

**Creation of junction**

Source item type:
- Folder: equivalent to MKLINK /J Link Target
- Network share: skip (which is not supported)
- Any others (e.g. file, system folder, folder in a ZIP file, query): skip

**Link name**

Same as source item name. Add a serial number before .extension if duplicated, i.e. (1), (2), ...

**Comment by tablacus** [comment]
I will try to consider it.

Regards,

**Comment by tablacus** [comment]
I have created a new add-on "Paste as link".
Please give it try.

Regards,

**Comment by ccfs** [comment]
Here are some findings:

**(A) Cannot create a link in some cases**

1. This version can create only one link. I expect that the add-on will process ALL ITEMS in the clipboard and create one link for each eligible item.

2. This version can process folder only. I expect that the add-on will also process FILES.

3. This version cannot create any link for a ROOT FOLDER (drive), although it seems to work.

4. This version cannot create any link when the link name is the same as an existing item in the destination folder. I expect that the add-on will add a SEQUENCE NUMBER in parentheses to the link name in order to create a link, e.g. "Photo (1).jpg".

**(B) Incorrectly attempt to create a link for an ineligible item**

1. This version incorrectly creates an inoperable link when the source item is
- an item in a ZIP file
- a system folder (e.g. Libraries)
Such items should be skipped.

2. This version incorrectly allows creation of a junction for a network share, which NTFS does not support, although finally no junction is created.

**(C) Clear-cut approach in path type of link target**

After a second thought, it may be better to enforce a "link target" (path) to match with the menu option chosen to avoid any confusion. Therefor the rules will be changed as follows:

1. If the source item is a network share, "Symbolic link, absolute path" must have been chosen. Otherwise it is skipped.

2. If the source and the destination are on different drives, "Symbolic link, absolute path" (file or folder) or "Junction" (folder only) must have been chosen. Otherwise it is skipped.

**(D) Windows problem in "absolute path without drive"**

If a link uses "absolute path without drive", the link target shown on Properties page may be incorrect, although the link will point to a correct target when used. I think this is probably a problem of Windows. So no action is required. Just let you know.

Regards,

**Comment by ccfs** [comment]
Here are the findings of version 1.01:

1. Still I can create only one link each time. I expect MULTIPLE.

2. You try to remove inapplicable menu items according to the item in the clipboard. This method is good only if the add-on processes one item each time. However I expect multiple, and the items in the clipboard can be a mixed of files, folders, network shares, items in different drives, etc. Therefore the add-on should simply show the menu in full, but skip creating a link if a source item fails the checks as stated in previous posts.

If any source item is skipped, the add-on should better show a message box telling the number of items skipped, and ask the user whether to view a LOG. The log will tell the reason for each skipped item. It will contain something like this:

`Paste as link to folder M:\TEST`
`Link type: Junction`

`C:\Windows\notepad.exe`_[tab]_`Not a folder`
`\\D2V\Share`_[tab]_`Network folder is not supported`

3. When the current (destination) folder is in a ZIP folder or a CLIP folder, the menu incorrectly shows up when the button is clicked.

4. A link to "LIBRARIES" system folder (which is inoperable) should NOT be allowed.
![lib](https://user-images.githubusercontent.com/34089121/120457330-f074e400-c3c8-11eb-97e1-c9e9fcc8684e.png)

5. If a source folder name contains a dot, the sequence number in the link name should be added at the END instead.
![seq folder](https://user-images.githubusercontent.com/34089121/120458433-dbe51b80-c3c9-11eb-97db-47c8a433d1f3.png)

6. If a source is a root folder (drive), the drive LETTER is missing when a sequence number is added to the link name.
![seq drive](https://user-images.githubusercontent.com/34089121/120458863-3aaa9500-c3ca-11eb-9ad3-3325eac7c91a.png)

7. A link to a network share CANNOT be created. Nothing happens after choosing the menu option. (But no problem for a folder in a network share.)

8. Junction CANNOT be created no matter the source is a folder or a drive. Nothing happens after choosing the menu option.

9. "Junction" option is removed when the source is in other file systems such as exFAT. This check is incorrect. A junction CAN point to a folder in non-NTFS.

Regards,

**Comment by ccfs** [comment]
I have tested version 1.02. Most problems above are solved.
The add-on now shows only applicable options by examining all items in the clipboard. This method is good.

I tried creating a link pointing to the destination folder itself. This was successful except when "relative path" was chosen. Some other links that were processed together could not be created too.
In reality such link is meaningless and may cause potential problems. Therefore I suggest that the add-on should NOT show any menu in this case (i.e. source item path = destination folder path), similar to the cases of system folders.

Regards,

**Comment by ccfs** [comment]
I have tested version 1.03. This version still allows creation of a link pointing to the its containing folder (i.e. source item path = destination folder path), except that "relative path" option is removed. This is not what I expect.

Of course you can allow this special case. But then the "relative path" option should be kept instead, as in version 1.02. The relative path should be ".", which I think version 1.02 has missed and thus cannot create the link.

Regards,

**Comment by ccfs** [comment]
The relative path problem is solved in version 1.04.

Another problem is found:
If the first source item is a file and the second is a folder, and the destination is on another drive, "Junction" option is incorrectly available.

Example:
Make sure the source items will be processed in the sequence in current file list.
![a0](https://user-images.githubusercontent.com/34089121/120912899-b7d55300-c6c5-11eb-9336-592b92b09fc3.png)
Copy a file and a folder to clipboard
![a1](https://user-images.githubusercontent.com/34089121/120912900-b9068000-c6c5-11eb-8627-2bdc64cd810f.png)
Switch to a folder on another drive and click the button
![a2](https://user-images.githubusercontent.com/34089121/120912901-b99f1680-c6c5-11eb-987c-38a52afe6dab.png)
"Junction" option is incorrectly available.

**Comment by ccfs** [comment]
In the above case, the file and then the folder are selected. This sequence seems to have an effect.

One more problem is found:
If the source items include a system folder (which is not supported) and a file/folder, the menu may incorrectly show up in certain cases.

Case 1:
Select "Recycle bin" and then a folder, and press Ctrl+C to copy
![D1](https://user-images.githubusercontent.com/34089121/120917734-676cee00-c6e3-11eb-860f-2c371f8126fa.png)
Switch to a folder on another drive. Click the button.
![D2](https://user-images.githubusercontent.com/34089121/120917737-6936b180-c6e3-11eb-9997-d95760c579c9.png)
The menu should NOT show up.

Case 2:
Select "Recycle bin" and then a file, and press Ctrl+C to copy
![FD1](https://user-images.githubusercontent.com/34089121/120917797-c468a400-c6e3-11eb-8cd9-8d37eb5b5919.png)
Switch to a folder on another drive. Click the button.
![FD2](https://user-images.githubusercontent.com/34089121/120917799-c599d100-c6e3-11eb-971b-ab3cfb0479d6.png)
The menu should NOT show up.

Case 3:
Select "Recycle bin" and then a file, and press Ctrl+C to copy
![FS1](https://user-images.githubusercontent.com/34089121/120917813-da766480-c6e3-11eb-8462-7c76a74ef2bd.png)
Switch to a folder on the same drive. Click the button.
![FS2](https://user-images.githubusercontent.com/34089121/120917815-dba79180-c6e3-11eb-8a4a-6732b8ad3d09.png)
The menu should NOT show up.

**Comment by ccfs** [comment]
Version 1.05 is OK. Although there are still some cases not handled gracefully, the add-on should be good for normal use. Thanks.
