### ISSUE TITLE
Tab plus - Clipboard content is unexpectedly replaced after moving a tab

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#295]
Please help to solve this problem. Thanks.

Copy something (a path) to clipboard
![1](https://user-images.githubusercontent.com/34089121/126285922-04b3bcde-2592-4624-82ab-e2bb29e4c4b2.png)
Move a tab by drag-and-drop
![2](https://user-images.githubusercontent.com/34089121/126285926-6d6a604e-86f6-499e-bcb5-4b2e78774853.png)
Paste the path to Notepad. Failed since the clipboard content had been unexpectedly replaced. 
![3](https://user-images.githubusercontent.com/34089121/126285931-83ca9f7e-cc15-40a8-b7c4-3c7514f55497.png)

**Comment by tablacus** [comment]
Please try to update an add-on "tab plus" 1.88.

Regards,

**Comment by ccfs** [comment]
The problem is solved by the new version. Thanks.
