### ISSUE TITLE
Shell execute hook not work

### ISSUE THREAD

**Issue by flier268** [tablacus/TablacusExplorerAddons#300]
The plugin not work on Windows 10 21H1
Maybe it had multi problem, I am not good at C++, so I don't check all of them.
One of issue is that it does not save exe path in `HKEY_CURRENT_USER\SOFTWARE\Tablacus\ShellExecuteHook\ExePath`, because 'HKEY_CURRENT_USER\SOFTWARE\Tablacus' does not exist.

I try to add the registry, but hook is not work same as before.

Table Explorer version: 21.11.1
Plugin version: 1.12
Windows version: Windows 10 21H1 build 19043.1320

**Comment by tablacus** [comment]
It is no longer possible to execute executable files with parameters using IShellExecuteHook.
I do not know if this is a bug or a specification of Windows.
IShellExecuteHook is now a deprecated shell API.
https://docs.microsoft.com/en-us/windows/win32/shell/deprecated-api

I will keep an eye on it and think of a way to deal with it.

Regards,

**Comment by flier268** [comment]
Can we use [SetWindowsHookExW](https://docs.microsoft.com/zh-tw/windows/win32/api/winuser/nf-winuser-setwindowshookexw)(WH_SHELL hook) to hook ShellExecute?

**Comment by tablacus** [comment]
I have adjusted it in Shell execute hook 1.13.
Please give it try.

Regards,

**Comment by tablacus** [comment]
I think SetWindowsHookExW(WH_SHELL hook) requires Tabracus Explorer to be running and is not a replacement for Shell execute hook.
It's more like [Open Instead](https://github.com/tablacus/TablacusExplorerAddons/wiki/openinstead).

**Comment by flier268** [comment]
register a windows service to do that？

**Comment by flier268** [comment]
> 
> 
> 我已經在 Shell execute hook 1.13 中對其進行了調整。 請試一試。
> 
> 問候，

Not work for me.
Is that work for you?

**Comment by tablacus** [comment]
It is work for me.
Let me know more details.
What situations aren't working for you?

https://github.com/tablacus/TablacusExplorer/wiki/report-problem

Regards,

**Comment by flier268** [comment]
TE64 21.11.1 Microsoft Windows 10 專業版 64 位元 21H1 (10.0.19043) Dark IE/11 JS/11.0.16384 zh_tw 120 AMD Ryzen 5 3600 6-Core Processor               Windows Defender

mouse 1.31,key 1.25,addressbar 1.68,filterbar 1.37,back 1.18,forward 1.18,up 1.20,treeview 1.41,toolbar 1.41,mainmenu 1.16,titlebar 1.09,tabplus 1.89,multithread 1.26,remember 1.40,undoclosetab 1.15,aboutblank 1.02,segoeicons 1.02,download 1.06,extract 1.14,drivebar 1.18,addonsupdater 1.09,preventduplicatetabs 1.17,lockedtabstop 1.08,labelbutton 1.15,innersearchbar 1.12,split 1.23,darkmode 1.09,history 1.17,favbar 1.27,recentlyclosedtabs 1.08,tasktray 1.15,mixedsort 1.13,closewhendeleting 1.03,everything 1.44,quicklook 1.07

![圖片](https://user-images.githubusercontent.com/19989232/140739030-4361943e-84bb-4351-a644-5ee626d44ffb.png)

Active three checkbox and restart computer, but it does not hook folder when I open folder in desktop.
