### ISSUE TITLE
Is there a way to set the columns for all folders

### ISSUE THREAD

**Issue by vouko** [tablacus/TablacusExplorerAddons#303]
Is there a way to set the list of columns to display for all the folders (i.e. everywhere) ? 

Apologies if this is not the right place to ask, but I could not find a forum or another place.

**Comment by vouko** [comment]
Btw, thank you for an amazing software.

**Comment by tablacus** [comment]
1. Please try to install an add-on "Take over folder view settings".
2. Disable folder settings add-ons (Remember folder view settings / Folder settings).

https://github.com/tablacus/TablacusExplorerAddons/wiki/takeoverfoldersettings

Regards,

**Comment by vouko** [comment]
Thank you. This seems to work, for each drive. Will further test.
