### ISSUE TITLE
Renamed tabs lose name when navigating away

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorerAddons#317]
Using the option to rename tabs when right-clicking a tab header and choosing the _Change Tab Name..._ (provided by the Tab Plus addon if I'm not mistaken) , I'm able to rename a tab title without issues.

If I navigate away from the folder I was currently in when renaming however, the title of the tab changes to the current folder name, until I'm back at the same folder I was in when I originally renamed the tab.

Is there a way or an option to make the tab names persistent and always display the custom assigned name regardless of the current folder, or associate the name to the tab itself rather than the current path?

**Comment by tablacus** [comment]
Not at this time.
It's possible if you make a script ... 

Regards,

**Comment by duarteframos** [comment]
Ah see, shame. What would I need to do through scripting, the rename action or the name itself?

**Comment by tablacus** [comment]
I have created an add-on "Fixed tab name".
Please give it try.

Regards,

**Comment by duarteframos** [comment]
Hell yess! It seems to be working like a charm.
Tab names are correctly kept when navigating away, reordering tabs, changing panes and are properly saved into the layout XML file, like they should, rather than a path list.

Great work, I'll document it right away in the wiki
