### ISSUE TITLE
Previewwindow 1.32

### ISSUE THREAD

**Issue by 3230** [tablacus/TablacusExplorerAddons#342]
I use tablacus evry day, and first time i thank you a lot for your very very good program !
I use this addon to listen a lot of short wav files and select witch i delete or keep (i m musician).
I would like to add some controls in this addon like : auto play, next file, stop...
And add mkv play.
Is it possible ? If yes how ? Thanks

**Comment by 3230** [comment]
I tryed to use visual studio to add some code, but can't add mkv player or new custom buttons.
Please can you help me or show me a way ? Is it possible to use libmpv or an other one better easy and that can play all audio an video files with control instead IE dll or mshtml or wmplayer ?
I think there a good thing to do here.
Have a great day !
From France.
Stef

**Comment by ccfs** [comment]
The add-on uses a built-in function of IE to play MP3 and MP4. For other media types, it uses WMP (Windows Media Player) EMBEDED in IE. The media types can be specified on options page.

![image](https://user-images.githubusercontent.com/34089121/178883959-44ac1a37-8c39-4799-b459-e39c7005f448.png)

If you still gets a problem, you can try to install "MKV codec", or update your version of WMP. See https://windowsreport.com/mkv-videos-windows-10/.

I have never tried the above suggestion, so I cannot guarantee this will work.

Adding controls to the window will involve enhancement to the add-on. I am not the application owner so I cannot help.

**Comment by 3230** [comment]
Thank you ccfs i will see that. It 's a start. Have a good day.

**Comment by ccfs** [comment]
Please try the new add-on [mpv](https://github.com/tablacus/TablacusExplorer/issues/705)

**Comment by 3230** [comment]
Ok ccfs thanks ! I will try that, have a good day!
