### ISSUE TITLE
 addon tooltippreview 1.27

### ISSUE THREAD

**Issue by 3230** [tablacus/TablacusExplorerAddons#343]
Hello !
It's a very good addon.
I need to enlarge the width and the heigh to see more text inside. How can i do that ?
I tryed to ad some code but nothing works...
Thank you for your help.
Have a good day.

**Comment by tablacus** [comment]
I'm not sure about details.
Could you give me an image like screenshot of what you want to do?

Regards,

**Comment by 3230** [comment]
Hi,
![ok](https://user-images.githubusercontent.com/32475279/182889527-d23d940e-6935-4f85-b51d-f4011591cfc6.jpg)

**Comment by tablacus** [comment]
I am not sure how to change this width.
In the meantime, how about QuickLook as an alternative?

Regards,

**Comment by 3230** [comment]
Thank you for your help !
Yes i could use QuickLook, i took the [3.7.1](https://github.com/QL-Win/QuickLook/releases/tag/3.7.1) version.
But i would stay in Tablacus Addon. For that moment i use Notepad++ for all text files.
I want to tell you, Tablacus explorer is better than all other explorer i've seen untill this day : apearance, customize, possibilities !
Good night !
