### ISSUE TITLE
Favorites bar / Side tree view - Hint about Height

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#349]
This proposed enhancement (see https://github.com/tablacus/TablacusExplorer/issues/633) is to provide users a hint about the input format of "Height" through a placeholder "Number or Percent%":

![fb](https://user-images.githubusercontent.com/34089121/211439148-d83dcfef-d719-41dc-81fc-3d660408bd8c.png)
![stv](https://user-images.githubusercontent.com/34089121/211439155-d68ec030-f0d8-4b89-a874-0bdefc38f978.png)

similar to "Auto update" add-on:
![au](https://user-images.githubusercontent.com/34089121/211439676-ec7c3690-b804-4d31-bad2-955b689a04b8.png)

@tablacus and @bblackmoor, please help to make the change. Thanks.

**Comment by bblackmoor** [comment]
I have created a fork, and I will dig into the code and look for this.

**Comment by bblackmoor** [comment]
I have found the code that creates that "Height" control. That is a straightforward edit.

However, neither the "Favorites Bar" addon nor the "Side Tree View" addon are in the main TablacusExplorer git repo. I do not know where they are. I do not see a git url on either page.

https://tablacus.github.io/wiki/addons/favoritesbar.html
https://tablacus.github.io/wiki/addons/sidetreeview.html


I am open to suggestions.

**Comment by ccfs** [comment]
I think the repo is https://github.com/tablacus/TablacusExplorerAddons. I am not a developer and I don't know the process to make a change.

The "Height" text box also appears in other places of TE and some other add-ons, but only the above 2 accept either a number or a percentage and have to be enhanced.

**Comment by bblackmoor** [comment]
Yes! I have forked that repo, and found the "Favorites Bar" addon and the "Side Tree View" addon. I will make the needed changes.

**Comment by bblackmoor** [comment]
I made the edit and pushed them to my fork. I am not sure what to do next. I clicked the"Contribute" button, and got the following response from it. I do not know what to do with this.

![image](https://user-images.githubusercontent.com/33701300/211680570-235283e6-fbf1-4412-947c-beaef168d197.png)

**Comment by ccfs** [comment]
The new version is OK. Thanks.
