### ISSUE TITLE
Using Total Commander File System Plug-in I can't find \\\

### ISSUE THREAD

**Issue by kh6011** [tablacus/TablacusExplorerAddons#359]
情報
TE64 23.1.12 Microsoft Windows 10 Enterprise 2016 LTSB 64 ビット (10.0.14393) WebView2/109.0.1518.70 JS/Chakra.dll ja 96 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz Windows Defender

アドオン
mouse 1.33,key 1.26,mainmenu 1.16,titlebar 1.09,tabplus 1.96,multithread 1.29,remember 1.42,undoclosetab 1.16,aboutblank 1.04,segoeicons 1.04,split 1.26,split9 1.04,split3 1.12,split6 1.10,split8 1.04,darkmode 1.18,previewwindow 1.32,quicklook 1.11,innernewfolder 1.06,innerrefresh 1.07,innerup 1.10,innerback 1.14,innerfilterbar 1.34,innerforward 1.16,innersearchbar 1.13,inneraddressbar 1.35,favbar 1.27,preventduplicatetabs 1.19,closewhendeleting 1.03,statusbar 1.19,sizestatus 1.27,startup 1.11,tabname 1.09,tabgroups 1.45,tabcolor 1.09,wfx 1.27,split12 1.00,t7zip 1.10

上記環境にて、
![image](https://user-images.githubusercontent.com/123920882/215387641-e4719246-6b81-4b10-9dc4-2dd9f69a484b.png)
という設定を実施しました。
そこで、アドレスに\\\を入力し、Enterキーを押下したところ、期待した表示ではなく、
![image](https://user-images.githubusercontent.com/123920882/215387761-eda3e327-0d3f-40d3-b2cd-6b9c8f6f67ce.png)
と表示されてしまいます。

対処法をご教示ください。

**Comment by tablacus** [comment]
とりあえず、Pre-release 版の23.1.31で調整しました。

https://github.com/tablacus/TablacusExplorer/releases/tag/23.1.31

アップデートしてみてください。
問題なければ明日位に正式版になって最新版の確認からアップデートできるようになる予定です。

**Comment by kh6011** [comment]
ご対応いただきましてありがとうございます。
事象が解消したことを確認いたしました。
