### ISSUE TITLE
Right button drag-and-drop menu - TypeError

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#360]
@tablacus, please solve the problem. Thanks.

TE64 23.1.31 Microsoft Windows 7 家用進階版  64-bit (6.1.7601) IE/11 JS/11.0.19597 zh_hk 96 Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
mouse 1.33,key 1.26,addressbar 1.70,back 1.18,forward 1.18,up 1.20,treeview 1.43,mainmenu 1.16,tabplus 1.96,restart 1.09,dragdropmenu 1.03
![0](https://user-images.githubusercontent.com/34089121/216491600-0c0aaaa4-e48e-4a73-9635-4a7407a7533b.png)
![1](https://user-images.githubusercontent.com/34089121/216491606-8a1a1a4f-d65b-42e6-ad9c-1464e1333dac.png)
![2](https://user-images.githubusercontent.com/34089121/216491611-6ec1c588-557c-40ac-8325-a11a2d609071.png)
![3](https://user-images.githubusercontent.com/34089121/216491612-3b156af7-57fa-4815-bc41-5c1871623564.png)

**Comment by ccfs** [comment]
@bblackmoor, please help to deploy the [patch](https://github.com/tablacus/TablacusExplorerAddons/files/10660016/dragdropmenu.fix.zip). Thanks.

**Comment by bblackmoor** [comment]
I am sorry, @ccfs My health keeps interfering with my desire to contribute. I think it would be best to forget about me for a while.

**Comment by ccfs** [comment]
The problem is solved with version 1.04.
