### ISSUE TITLE
Add-on failure -“Force refresh”and “close tab when deleting”

### ISSUE THREAD

**Issue by yaolion** [tablacus/TablacusExplorerAddons#362]
The expansion problem mentioned on the Tablacus Explorer page has not been solved.
https://github.com/tablacus/TablacusExplorer/issues/628

system is win11 22h2

“Force refresh”-Dragging files from different windows cannot take effect immediately

“close tab when deleting”-Doesn't work

**Comment by yaolion** [comment]
I modified the code myself to meet my own needs

**Comment by ccfs** [comment]
"Close tab when deleting" add-on has been patched.
