### ISSUE TITLE
Everything 1.5 Alpha does not work with the existing everything addon

### ISSUE THREAD

**Issue by herbrot** [tablacus/TablacusExplorerAddons#367]
for some years Everything 1.5 Alpha is in development and I use it for half a year (there are some great new features).
But if I select this version in the eveverything addon the search window is alway empty.

In procmon I can see the program is started by tablacus.
Unfortunately my skills are not good enough to find out what is going wrong.

**Comment by tablacus** [comment]
Please try to update "Everything" add-on v1.46.

Open an options of "Everything" add-on.

Enter `EVERYTHING_TASKBAR_NOTIFICATION_(1.5a)` to Class field.

![image](https://github.com/tablacus/TablacusExplorerAddons/assets/5156977/0ec9cd10-5420-4bca-8c1e-ea510433f21f)

This is probably a provisional specification for the Alpha version of Everything, so please revert to the original when you get to the Release version.

Regards,

**Comment by herbrot** [comment]
Thank you so much for the quick response.
Works perfectly

Regards
