### ISSUE TITLE
Script Error with Background Image addon on startup

### ISSUE THREAD

**Issue by TheMidnightSnack** [tablacus/TablacusExplorerAddons#369]
Hello, 
With the Background Image addon enabled, I receive a script error when opening TE. 

![Untitled](https://github.com/tablacus/TablacusExplorerAddons/assets/40611738/0939faf8-28c7-4d79-8681-495b01746f33)

The background image also disappears when leaving and returning to the directory.
I am unsure if this is a bug or just the nature of the addon.

Running:
TE64 23.9.13 Microsoft Windows 10 Pro 64-bit 22H2 (10.0.19045) IE/11 JS/11.0.16384 en_us 96 AMD Ryzen 7 5700X 8-Core Processor              Windows Defender

with Addons:
bgimage 1.09,tabdesign 1.16,mouse 1.33,key 1.26,addressbar 1.71,filterbar 1.39,back 1.18,forward 1.18,up 1.20,treeview 1.44,refresh 1.10,toolbar 1.44,mainmenu 1.16,titlebar 1.09,tabplus 1.96,multithread 1.29,remember 1.42,undoclosetab 1.16,aboutblank 1.04,foldericon 1.04,classicstyle 1.10,openinstead 1.13,stripeslite 1.09,tasktray 1.15,startup 1.11,framepane 1.02

**Comment by ccfs** [comment]
1. Script error: I cannot reproduce the error. Anyway I have made a change according to a probable cause.
2. Background image disappeared: I have made a change.

Pleases try this [patch](https://github.com/tablacus/TablacusExplorerAddons/files/13916509/bgimage_109.patch.zip) and see.

**Comment by ccfs** [comment]
This [revised patch](https://github.com/tablacus/TablacusExplorerAddons/files/13920625/bgimage_109.patch.zip) may be better. Please let me know the result. Thanks.

**Comment by TheMidnightSnack** [comment]
The patch you provided has fixed the disappearing background issue well.
However, I am now receiving this error:
 
![Untitled](https://github.com/tablacus/TablacusExplorerAddons/assets/40611738/4a8ac8a7-460b-4aa4-9595-d3f0fabaf699)

After experimenting with disabling my other addons, I found the error only appears when the Startup Settings addon is enabled with the option of 'Close other tabs', as described by @tablacus in https://github.com/tablacus/TablacusExplorerAddons/issues/25#issuecomment-371120543

![asd](https://github.com/tablacus/TablacusExplorerAddons/assets/40611738/a6182d0a-7556-4430-8c0e-05d0d36e54d9)

The two addons seem to be conflicting each other at startup.

**Comment by ccfs** [comment]
I have further revised the [patch](https://github.com/tablacus/TablacusExplorer/files/13927412/bgimage_109.patch.zip). The above problem should be solved.

**Comment by TheMidnightSnack** [comment]
Issue resolved, patch works well.

**Comment by ccfs** [comment]
I have updated the [patch](https://github.com/tablacus/TablacusExplorerAddons/files/15092330/bgimage_109.patch.zip) since the previous one gets an error under WebView.
