### ISSUE TITLE
Problems with display and selection when drive bar add-on is enabled

### ISSUE THREAD

**Issue by splash70** [tablacus/TablacusExplorerAddons#372]
いつもありがたく使用させていただいています。
ドライブバーアドオンをインストールした際の問題かと思いますが、例えば、以下のように設定して

　　ツールバー１左　　メインメニュー
　　ツールバー１中央　お気に入りバー(水平)、分割、３分割、６分割
　　ツールバー１右　　ドライブバー
　　ボトムバー左　　　ステータスバー
　　ボトムバー右　　　サイズ情報バー

ツールバー１中央が収まりきらないようなウィンドウサイズにすると、中央が２段で表示されますが、次回起動時に２段目が選択できず、ボトムバーの表示もされないようです。

ウィンドウサイズを変更すると、ツールバー中央の２段目が選択できるようになり、ボトムバーも表示されます。

ドライブバーをインストールしなければ問題無いようです。

以前はこのようなことは無かったように思いますが、どこかの更新からこうなりました。
新規に最新版をインストール、というか新規に展開して新しい環境を作っても同様です。

何かの折にご確認とご対応いただけると幸いです。

**Comment by tablacus** [comment]
ドライブバー1.19で調整しました。アップデートしてみてください。
ダメなようならば、ヘルプ(H)→Tablacus Explorerについて(A)のダイアログの情報の所の情報や中央が2段で表示されているときと次回起動時の問題がある画面のスクショ（個人情報等があれば塗りつぶしてもらって)アップしていただけると幸いです。

**Comment by splash70** [comment]
ドライブバー1.19で問題解消されていることを確認しました。
早速のご対応ありがとうございました。

本体とアドオンで投稿する場所が違うことに気づかず、失礼しました（汗
