### ISSUE TITLE
Window Alpha - Default value not set properly

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#374]
@ffbeso,

The add-on has a small problem. The default value is not set properly. Example:

(1) Enable the add-on the first time, WITHOUT going to its options page.
![1](https://github.com/tablacus/TablacusExplorerAddons/assets/34089121/9a962592-775a-4381-b54b-58ecb5974bb7)

(2) The add-on works correctly (alpha = 230). 
![2](https://github.com/tablacus/TablacusExplorerAddons/assets/34089121/4b791ada-c570-4c8f-a77a-e549854189af)

(3) Go to its options page. Current alpha value is NOT 230.
![3](https://github.com/tablacus/TablacusExplorerAddons/assets/34089121/0f87917c-3242-4cbc-b046-9d4d70be0a0e)

May I suggest you to refer to "Fire File Copy" add-on (or some others) for the way to set a numeric default value properly.

Thanks.

**Comment by ffbeso** [comment]
@ccfs, Thanks for the report.
I was missing the initial value in the options settings.
I've made a pull request for a modified version.
https://github.com/tablacus/TablacusExplorerAddons/pull/375#issue-2216434704

**Comment by ccfs** [comment]
I tried the new version 1.01 with the above steps. Sorry, still a small problem.

At step (3), although the page showed 230, but after I clicked OK, "alpha" ended up 128.

(3) Options page
![3](https://github.com/tablacus/TablacusExplorerAddons/assets/34089121/59392571-9e31-4d65-aa39-d89554930ca5)

(4) After clicking OK, alpha value = 128
![4](https://github.com/tablacus/TablacusExplorerAddons/assets/34089121/a673bab5-9491-4b79-bc63-900ca010e8f5)

**Comment by ffbeso** [comment]
@ccfs, Thanks for checking.
It is indeed incomplete.
I had to set an initial value for the range input as well.

**Comment by ccfs** [comment]
New version 1.02 is OK. Thanks.
