### ISSUE TITLE
How to output Log when developing a plug-in?

### ISSUE THREAD

**Issue by qian-jiahong** [tablacus/TablacusExplorerAddons#379]
When developing a plug-in, debugging is required. How to output Log?

**Comment by ccfs** [comment]
Use "Debug" add-on.
See the [pdf](https://github.com/ccfs/TablacusExplorer/issues/1) for details.
If you are debugging an options page (options.js), you may need to prefix the statement with MainWindow. e.g. MainWindow.Addons.Debug.alert
The add-on displays messages on the Debug pane only.
Here is a [temp version](https://github.com/tablacus/TablacusExplorerAddons/files/15467048/debug.zip) of the add-on which will write messages to a log file.
The add-on cannot run under WebView though.
