### ISSUE TITLE
Feature request: Add "administrative tools" to the systemfolders add-on

### ISSUE THREAD

**Issue by centsi** [tablacus/TablacusExplorerAddons#38]
Hi - although "administrative tools" can be reached by going through the control panel folders, for me it would be very useful for it to be directly in the list of folders in the systemfolders add-on.

Tablacus is excellent by the way. 👍

Thanks - Lawrence

**Comment by tablacus** [comment]
I've adjusted an add-on "System folder" 1.01.

How anout this?
![image](https://user-images.githubusercontent.com/5156977/47788997-b184da80-dd56-11e8-936f-e68a16923f34.png)

And, you can use Administrative Tools anywhere using "shell:Common Administrative Tools".
For example, Tool bar.
![image](https://user-images.githubusercontent.com/5156977/47789305-91a1e680-dd57-11e8-9c3b-c00f34b714ff.png)

Regards,

**Comment by centsi** [comment]
Excellent, thanks.
