### ISSUE TITLE
Window Fadeout - SyntaxError

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#384]
@ffbeso,

I tried the add-on but got an error.
![20240730_155730](https://github.com/user-attachments/assets/273d1f87-7bf9-4db3-a665-117ce3f565ce)

TE64 24.7.28 Microsoft Windows 7 家用進階版  64-bit (6.1.7601) IE/11 JS/11.0.19597 zh_hk 96 Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
mouse 1.33,key 1.26,addressbar 1.73,filterbar 1.39,back 1.18,forward 1.18,up 1.20,treeview 1.47,toolbar 1.44,mainmenu 1.16,titlebar 1.09,tabplus 1.97,multithread 1.29,remember 1.42,segoeicons 1.04,restart 1.09,windowfadeout 1.1

**Comment by ccfs** [comment]
Besides, you may put the captions on Options page (e. g. Alpha, FadeInStep, etc.) within <label> and </label> so that they can be translated with an external language XML file.

**Comment by ffbeso** [comment]
I committed the revised version [here](https://github.com/tablacus/TablacusExplorerAddons/pull/382/commits/cff7f987b6c67f6cb3525f7df8139f0866a6df7d).
I also tried to support the translation files that were suggested

**Comment by ccfs** [comment]
The new version runs successfully under IE and WebView.
Translation is also successful.
Thanks.
