### ISSUE TITLE
Window Alpha 1.03 - Alpha value incorrectly reverts

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#386]
@ffbeso,

After I changed the alpha value, TE window did not change.
![1](https://github.com/user-attachments/assets/fea3d71d-13ad-41c1-8519-691d90b401a4)
![2](https://github.com/user-attachments/assets/d78cbaf3-b77b-4961-93de-3d28aa50ff81)

I went back to the Options page, alpha value reverted to 230, and the slide did not reflect the actual value.
![3](https://github.com/user-attachments/assets/86a5d07b-454a-4d82-bc82-5fc96932b60d)

**Comment by ffbeso** [comment]
Oh no, I tried to unify the variable naming notation with CamelCase and there was a omission. Thanks for the report.

**Comment by ccfs** [comment]
New version 1.04 is OK under both IE and WebView. Thanks.
