### ISSUE TITLE
Clip folder - can't launch OBS.

### ISSUE THREAD

**Issue by veksha** [tablacus/TablacusExplorerAddons#388]
![image](https://github.com/user-attachments/assets/feef3432-4f2c-497a-b7e0-fb089f95fd7d)

added obs64.exe to my "clip" folder but it can't be launched correctly:

![image](https://github.com/user-attachments/assets/0c5822b3-25d9-4da6-bb44-cda74ed1b7c2)

there is no problem launching it from Windows' Run dialog. so the problem is within Tablacus Explorer.

PS:
commented out last line inside "te.OnDefaultCommand" function in "sync1.js" file and the problem is gone.
```js
//return InvokeCommand(Selected, 0, te.hwnd, null, null, null, SW_SHOWNORMAL, 0, 0, Ctrl, CMF_DEFAULTONLY);
```

Found this randomly, so i don't know what i'm doing. Asking you to fix it by yourself. Thanks!

**Comment by ccfs** [comment]
Please copy and paste your TE info from "Help > About Tablacus Explorer" into your reply, and show the steps to produce the error with screen captures. Please also post the CFU file (zip it so that it can be posted).

**Comment by veksha** [comment]
About Tablacus:
TE64 24.8.6 Майкрософт Windows 11 Pro 64-разрядная 22H2 (10.0.22621) IE/11 JS/11.0.16384 ru_ru 120 AMD Ryzen 7 2700 Eight-Core Processor           Windows Defender
mouse 1.33,key 1.26,filterbar 1.39,up 1.20,toolbar 1.44,mainmenu 1.16,titlebar 1.09,tabplus 1.97,multithread 1.29,remember 1.42,segoeicons 1.04,download 1.08,innerbreadcrumbsaddressbar 1.53,darkmode 1.19,noinfotip 1.02,history 1.20,rememberselection 1.04,tabcolor 1.09,previewwindow 1.33,split 1.26,undoclosetab 1.18,clipfolder 1.28,innernewfolder 1.06,sizestatus 1.27,addonsupdater 1.10,autoupdate 1.03,switchpane 1.05,controlpanelbutton 1.10,addonswitcher 1.03,mpv 1.01

.cfu file: [clip folder obs.zip](https://github.com/user-attachments/files/17256638/clip.folder.obs.zip)

steps:
1. open tablacus, get `clipfolder` addon, create "clip" folder (by selecting "create clip folder" from right-click menu).
2. download OBS software (free and open source).
3. go to OBS folder and drag obs64.exe file to your new "clip" folder.
4. launch obs64.exe from "clip" folder. you will get OBS error: failed to find locale.

![image](https://github.com/user-attachments/assets/1ea597e9-4a0e-46c1-ac9c-4422833774e1)
![image](https://github.com/user-attachments/assets/2584d751-8a24-4cde-b37b-01497d1468f8)

**Comment by tablacus** [comment]
I have adjusted it on [Tablacus Explorer 24.10.4](https://github.com/tablacus/TablacusExplorer/releases/tag/24.10.4).

We will monitor the situation for a day or so, and if there are no problems we will officially release it.

Regards,

**Comment by veksha** [comment]
i think it works good now. thanks!
