### ISSUE TITLE
Speed Dial / Duplicate tab

### ISSUE THREAD

**Issue by tithom** [tablacus/TablacusExplorerAddons#42]
Hello,
The new tab button allows to duplicate a tab. When the addon speed dial is installed, it open instead recent directories and we loose this option.
Is there a way to add in the contextual menu of tabs an entry "Duplicate tab" ? Perhaps include this in the speed dial addon ?
Thanks.

**Comment by tablacus** [comment]
I've adjusted it on Speed dial 1.09.
Please try to install it.

1. Open options of "Speed dial".

![image](https://user-images.githubusercontent.com/5156977/48417248-a3db4600-e795-11e8-8342-984695e5e5de.png)

2. Uncheck Replace -> New tab

![image](https://user-images.githubusercontent.com/5156977/48417357-e2710080-e795-11e8-85e4-4929a1bff8fd.png)

Regards,

**Comment by tithom** [comment]
Sorry for the response delay, thanks for the fast update! Question: with this option active, how can I access the fast dial page? I need to add a specific bookmark? (that's why I didn't answer sooner, I wanted to look for it a bit and then I forgot).
What does the "Add / Menus" do? I didn't see any impact.

**Comment by tablacus** [comment]
To access the Speed dial page navigate "about:newtab".

* "Add / Menus"
![image](https://user-images.githubusercontent.com/5156977/48904508-f0afd280-eea1-11e8-9d92-2c81b55afd2f.png)

* Script to open duplicate tab anyway

Type
`JScript`

Options
```
FV = GetFolderView(Ctrl, pt);
FV.Navigate(FV.FolderItem, SBSP_NEWBROWSER);
```

![image](https://user-images.githubusercontent.com/5156977/48904718-9bc08c00-eea2-11e8-99b6-b442d46227b7.png)

Regards,

**Comment by tithom** [comment]
Oh ok, indeed, thanks!
