### ISSUE TITLE
TypeError in "Folder large icon changer"

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#44]
If no icon file is specified in the configuration page, when I change the view to medium icon (or larger) while the current folder is C:\Windows\Media, an error message box shows:
![error](https://user-images.githubusercontent.com/34089121/49135814-d737dc00-f322-11e8-81b2-fa38705f59b0.png)
I suggest to fix this by using a default folder icon if no icon file is specified.

Regards,

**Comment by tablacus** [comment]
Thank you for the report.
I've adjusted it on Folder large icon changer 1.02.

Best regards,

**Comment by ccfs** [comment]
I have tried the new version but the problem is still here.
![image](https://user-images.githubusercontent.com/34089121/49267506-d6738700-f495-11e8-9643-5f54b03f7001.png)

**Comment by tablacus** [comment]
Thank you for your report.
I've adjusted it again on Folder large icon changer 1.03.

Thanks a bunch,

**Comment by ccfs** [comment]
Tested OK. Thanks.
