### ISSUE TITLE
Script error on Mouse add-on config page

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#47]
Select any record
![image](https://user-images.githubusercontent.com/34089121/49919449-983c8580-fee1-11e8-8937-742dce0c2e05.png)
Double-click the record, or double-click an empty space of the record list. TE shows a script error.
![image](https://user-images.githubusercontent.com/34089121/49919487-bc986200-fee1-11e8-82f9-de61903c5075.png)
Please help to solve this problem.

**Comment by tablacus** [comment]
I have adjusted it on Mouse 1.24.
Please try to install it.

Regards,

**Comment by ccfs** [comment]
Tested OK. Thanks.
