### ISSUE TITLE
Total Commander Lister Plug-in - settings not saved

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#48]
Open the config page
![image](https://user-images.githubusercontent.com/34089121/49919668-55c77880-fee2-11e8-842a-1c96b37b84b9.png)
Use Up and Down button to move the records, or Remove button to delete any record
![image](https://user-images.githubusercontent.com/34089121/49919697-755ea100-fee2-11e8-9dfb-8e1f4ef2073a.png)
Click OK to save the changes. Then re-open the page.
![image](https://user-images.githubusercontent.com/34089121/49919714-84ddea00-fee2-11e8-9e01-b4b59e67d155.png)
The changes are lost.
Please help to solve this problem.

**Comment by tablacus** [comment]
I have adjusted it on Total Commander Lister Plug-in 1.06.
Please try to install it.

Regards,

**Comment by ccfs** [comment]
Tested OK. Thanks.
