### ISSUE TITLE
open new tab with list of devices

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorerAddons#5]
Hi,
I'm using tabplus addon, and I'd like to open new tabs that show the list of devices, just like "My Computer". Is there an option to set the default for new tabs? Thank you.

**Comment by tablacus** [comment]
I will adjust it on the next update.
Best regards,

**Comment by stefanocaselli** [comment]
Wonderful!
Thanks.


2015-01-26 12:06 GMT+01:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
I adjust it on Tablacus Explorer 15.2.1

Choose Tools -> Options. 
![150201_01](https://cloud.githubusercontent.com/assets/5156977/5992339/d2c6edd4-aa68-11e4-8375-448e3339e9ad.png)

Click "Tabs" on left side.
![150201_02](https://cloud.githubusercontent.com/assets/5156977/5992345/0e7ad6ce-aa69-11e4-9555-84515aa50a9b.png)

Click the "Reference..." button of New Tab.
![150201_03](https://cloud.githubusercontent.com/assets/5156977/5992348/3ed6d340-aa69-11e4-9d2a-0f74013551ba.png)

Click "Desktop"
![150201_04](https://cloud.githubusercontent.com/assets/5156977/5992349/5024d3ea-aa69-11e4-994b-003423fc4f63.png)

Click "This PC" or "My Computer", then click the "Open" button.
![150201_05](https://cloud.githubusercontent.com/assets/5156977/5992353/7987049c-aa69-11e4-9a47-d70adba019f0.png)

Click the "OK" button to be completed. 
![150201_06](https://cloud.githubusercontent.com/assets/5156977/5992363/b8b78380-aa69-11e4-9beb-fdce87c57b5d.png)

**Comment by stefanocaselli** [comment]
Hi,
the new option works perfectly. Thank you!
I have a bug report, however: strangely in details view I cannot see the size for zip files:
![cattura](https://cloud.githubusercontent.com/assets/10347571/6008455/ebfff322-ab21-11e4-9b32-29d95b3715ad.PNG)

**Comment by tablacus** [comment]
Thank you for your report.
Is this Total file size?
Probably I think that this is because ZIP is virtual Folder.
I will adjust it on the next update.

**Comment by stefanocaselli** [comment]
yes it's total file size. but on my pc the zip files are associated to 7zip, not with virtual folder.

**Comment by tablacus** [comment]
I adjust it on Tablacus Explorer 15.2.3
Best regards,

**Comment by stefanocaselli** [comment]
yes it works. thank you again.


2015-02-03 15:35 GMT+01:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
You are welcome.
