### ISSUE TITLE
Addon "colored with extension" does not work anymore

### ISSUE THREAD

**Issue by Fragden** [tablacus/TablacusExplorerAddons#55]
Hallo

since the update to 1.03 this addon does not work anymore. Any idea? 
Is there a need to put any special character together with the extension?

Environment:

TE64 19.1.8 Win 10.0.16299 WS 100 IE 11 de_de 96 Kaspersky Endpoint Security 10 für Windows Windows Defender

addressbar,filterbar,up,treeview,mainmenu,tabplus,multithread,remember,undoclosetab,tabcolor,tabname,color,mouse,linkbar,split,addonsupdater,tabcolorplus,inactivepane,extensioncolor

Regards

**Comment by tablacus** [comment]
It seems no problem for me.
Please be more specific about it?

![image](https://user-images.githubusercontent.com/5156977/50975498-1f0c6e80-1531-11e9-9c35-5021b50ac3cc.png)

![image](https://user-images.githubusercontent.com/5156977/50975519-2b90c700-1531-11e9-853f-ca3879e9fabf.png)

Regards,

**Comment by Fragden** [comment]
I don't what other information can I give you. Before Christmas it was working, but now no more...

![colored with extension error](https://user-images.githubusercontent.com/18126517/51040799-b668d480-15b8-11e9-84a5-96eb486eb341.PNG)

**Comment by tablacus** [comment]
Please try to unckeck Options -> List -> Explorer browser -> Details.

![image](https://user-images.githubusercontent.com/5156977/51071553-213c0d80-1696-11e9-8cc7-40246b60b9a1.png)

_When you check Explorer browser, the folder view is displayed exactly like Explorer, so some add-ons will not work._

Regards,
