### ISSUE TITLE
Tab groups 1.05 with older IE:"Object doesn't support property or method 'preventDefault'".

### ISSUE THREAD

**Issue by bogota** [tablacus/TablacusExplorerAddons#6]
On my Win7 box with Internet Explorer 10, almost all operations of dragging and swapping positions of group tabs fail with an error dialog "Object doesn't support property or method 'preventDefault'".

After updating to IE11 all has come to work fairly well so it has to be relevant to some IE compatibility issue.

**Comment by tablacus** [comment]
I will look further into it based on this information.
Thank you.

**Comment by tablacus** [comment]
I've adjusted it on Tab groups 1.07
Best regards,
