### ISSUE TITLE
"Download" add-on not work with cURL

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#68]
1. Set up the add-on with cURL
![c-1](https://user-images.githubusercontent.com/34089121/52328988-76b4d180-2a2c-11e9-896f-937705c50b18.png)
2. Choose "Help > Check for updates"
![c-2](https://user-images.githubusercontent.com/34089121/52328989-76b4d180-2a2c-11e9-9ea1-fe08cf8eb4b4.png)
3. TE asks to install an update version. Click OK.
![c-3](https://user-images.githubusercontent.com/34089121/52328990-76b4d180-2a2c-11e9-80f4-b32de8417268.png)
4. TE shows "Please wait".
![c-4](https://user-images.githubusercontent.com/34089121/52328991-774d6800-2a2c-11e9-857b-91168580609e.png)
But then nothing happens even after I click "OK". At last I have to click "Cancel".

Please help to solve this problem.

**Comment by tablacus** [comment]
I have adjusted it on Download 1,02
Option of "-L" in cURL is required.

![image](https://user-images.githubusercontent.com/5156977/52346246-89e29400-2a62-11e9-9568-f00e311a0d64.png)

**Comment by ccfs** [comment]
Tested OK. Thanks.
