### ISSUE TITLE
"Download" add-on not work with "Add-ons updater"

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#69]
1. Set up the add-on with BITSAdmin
![ao-0](https://user-images.githubusercontent.com/34089121/52329368-94cf0180-2a2d-11e9-9678-679bcda79aaa.png)
2. "Add-ons updater" is enabled.
![ao-1](https://user-images.githubusercontent.com/34089121/52329369-94cf0180-2a2d-11e9-87c3-9ef686efb081.png)
3. An update version is available for an add-on
![ao-2](https://user-images.githubusercontent.com/34089121/52329370-95679800-2a2d-11e9-824e-1e15f4af8e1a.png)
4. Choose "Help > Check for updates"
![ao-3](https://user-images.githubusercontent.com/34089121/52329371-95679800-2a2d-11e9-985f-f1b82b94be9f.png)
5. TE asks to install an update version. Click OK.
![ao-4](https://user-images.githubusercontent.com/34089121/52329372-95679800-2a2d-11e9-8d72-b64cd9a3593d.png)
6. TE is updated.
![ao-5](https://user-images.githubusercontent.com/34089121/52329373-96002e80-2a2d-11e9-86d5-3925009af8ed.png)
7. But the add-on is not updated. 
![ao-6](https://user-images.githubusercontent.com/34089121/52329374-96002e80-2a2d-11e9-8fa6-33aefb68e4cf.png)

Please check if this issue can be solved. Thanks.

**Comment by tablacus** [comment]
I have adjusted it on Add-ons updater 1,05
Please try to update.

Regards,

**Comment by ccfs** [comment]
Tested OK. Thanks.
