### ISSUE TITLE
Tab plus 1.17:right click doesn't work

### ISSUE THREAD

**Issue by bogota** [tablacus/TablacusExplorerAddons#7]
Right-clicking on tabs fails to show any context menus when:

- Tab plus is enabled and
- Options->General->Mouse->Gestures is set to 'Priority'.

**Comment by tablacus** [comment]
Thank you for your information.
I will adjust it in the next version of Tablacus Explorer.
Best regards,

**Comment by tablacus** [comment]
I've adjusted it on Tablacus Explorer 15.3.12
Best regards,

**Comment by bogota** [comment]
Now it works. Thanks for your effort.

**Comment by tablacus** [comment]
My pleasure.
