### ISSUE TITLE
Remove Options page of "Multiple Executions"

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#70]
Suggest to remove the Options of this add-on, as they are useless but might confuse users.
![image](https://user-images.githubusercontent.com/34089121/52331738-e5e1f400-2a33-11e9-9dcf-b9c24e8b0f67.png)

**Comment by tablacus** [comment]
I have adjusted it on Multiple executions 1.01
Thank you,

**Comment by ccfs** [comment]
Tested OK. Thanks.
