### ISSUE TITLE
tabplus: slowly dragging the active tab does not update the tab titles

### ISSUE THREAD

**Issue by char101** [tablacus/TablacusExplorerAddons#78]
How to reproduce:

1. open 3 tabs: A B C
2. set B as the active tab
3. press left mouse button on B tab and wait for 3 seconds, then drag B into C
4. the tab titles will still be A B C with C being the active tab
5. click on A, the tab titles will now be A C B

**Comment by tablacus** [comment]
Are you using an add-on "Tab plus"?
[When reporting a problem, please be specific.](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt)

Best regards,

**Comment by char101** [comment]
Hi,

Yes, that's why I prefixed the title with the addon name: `tabplus:`.

**Comment by tablacus** [comment]
I've adjusted it on Tab plus 1.48.
Please try to update it.

Regards,

**Comment by char101** [comment]
Thanks, dragging the current tab works great now.
