### ISSUE TITLE
Old version of 'Tab Parent Folder Name'

### ISSUE THREAD

**Issue by guilhas** [tablacus/TablacusExplorerAddons#8]
Hello,

When I download new version of tablacus
And try to install the plugin 'Tab Parent Folder Name'
It shows version 1.00

![image](https://cloud.githubusercontent.com/assets/456810/19318408/7f112afe-90a0-11e6-9f6c-fc4a5d4b7884.png)

In older tablacus and github repository version is 1.01
[https://github.com/tablacus/TablacusExplorerAddons/blob/master/tabparentname/config.xml](https://github.com/tablacus/TablacusExplorerAddons/blob/master/tabparentname/config.xml)

**Comment by tablacus** [comment]
Thank you. I have corrected this.

**Comment by guilhas** [comment]
Thank you. Working as expected.
