### ISSUE TITLE
tabplus: show the full path as tooltip

### ISSUE THREAD

**Issue by char101** [tablacus/TablacusExplorerAddons#82]
Hi,

Is is possible to show the full path as tooltip when hovering the tab in the tabplus addon.

Reason: so that the user can know the path of a tab without having to select it first.

Thanks.

**Comment by tablacus** [comment]
Tab plus's options -> Tooltips
![image](https://user-images.githubusercontent.com/5156977/54614538-ec867100-4a9f-11e9-8e86-2e01f80c6c40.png)

Regards,

**Comment by char101** [comment]
Thank you and sorry, should have checked the settings first.
