### ISSUE TITLE
Request preventduplicatetabs

### ISSUE THREAD

**Issue by guilhas** [tablacus/TablacusExplorerAddons#9]
Hello,

When I open a folder which duplicated tab, it gets closed, and focus on the already open one.

Would it be possible to move, that already opened tab, to the end of the tab bar or to the position of the closed tab? Like a recently opened tab.

So if there are 30 tabs open you will know that you are working on the most recent one, instead of getting transported to the middle of other unrelated tabs.

Can be a optional configurable setting
Only if tab not locked maybe

Regards,
Lino

**Comment by tablacus** [comment]
Hello,
So, do you want to leave a new tab position and to close older tab position?

Open "Addons"　from here
![3](https://cloud.githubusercontent.com/assets/5156977/19931052/73ad2c26-a14e-11e6-8309-c327f3994dfa.png)

Now tab position
![4](https://cloud.githubusercontent.com/assets/5156977/19931075/8e358ad4-a14e-11e6-875d-ce4a99f3262f.png)

Like this?
![5](https://cloud.githubusercontent.com/assets/5156977/19931103/acaa2ed4-a14e-11e6-9655-1e01c0df3c38.png)

I will try to consider it.
Best regards,

**Comment by guilhas** [comment]
Yes that's it.

Although I am not sure if you should close the old VS close the new and move the old. To preserve filters in the tab, order, or other stuff. But speed wise closing the old would be faster.

**Comment by tablacus** [comment]
I've adjusted it on Prevent Duplicate Tabs 1.05.
Best Regards,

**Comment by guilhas** [comment]
Thanks. Looks good.

Best regards,
Lino
